import { z } from "zod";

export const CURRENT_SCHEMA_VERSION = 34;

const gameDateSchema = z.object({
  year: z.number().int().min(1900).max(2200),
  month: z.number().int().min(1).max(12),
  day: z.number().int().min(1).max(31),
});

const personalitySchema = z.object({
  preset: z.enum(["obsessed", "composed", "electric", "underdog"]),
  discipline: z.number().min(0).max(100),
  ambition: z.number().min(0).max(100),
  confidence: z.number().min(0).max(100),
  composure: z.number().min(0).max(100),
  coachability: z.number().min(0).max(100),
  adaptability: z.number().min(0).max(100),
  riskTolerance: z.number().min(0).max(100),
  approvalNeed: z.number().min(0).max(100),
});

const characterSchema = z.object({
  identity: z.object({
    firstName: z.string().min(1),
    lastName: z.string().min(1),
    fullName: z.string().min(3),
    birthDate: z.string().min(10),
    age: z.number().int().min(15).max(22),
    gender: z.enum(["male", "female"]),
    handedness: z.enum(["right", "left"]),
  }),
  origin: z.object({
    country: z.literal("USA"),
    stateCode: z.string().length(2),
    stateName: z.string().min(2),
    city: z.string().min(2),
    region: z.string().min(2),
    familyIncome: z.enum(["strained", "working", "comfortable", "wealthy"]),
    familyStructure: z.enum(["two-parent", "single-parent", "extended-family"]),
    familySupport: z.enum(["demanding", "supportive", "hands-off"]),
    neighborhoodSafety: z.number().min(0).max(100),
    schoolQuality: z.number().min(0).max(100),
    trainingAccess: z.number().min(0).max(100),
    medicalAccess: z.number().min(0).max(100),
    footballCulture: z.number().min(0).max(100),
  }),
  personality: personalitySchema,
  physical: z.object({
    heightInches: z.number().int().min(60).max(84),
    weightLbs: z.number().int().min(130).max(360),
    frame: z.enum(["compact", "balanced", "long", "powerful"]),
    speed: z.number().min(0).max(100),
    strength: z.number().min(0).max(100),
    agility: z.number().min(0).max(100),
    stamina: z.number().min(0).max(100),
    explosiveness: z.number().min(0).max(100),
  }),
  education: z.object({
    gpa: z.number().min(0).max(4),
    academicAbility: z.number().min(0).max(100),
    attendance: z.number().min(0).max(100),
    eligibilityStatus: z.enum(["clear", "watch", "at-risk"]),
  }),
  condition: z.object({
    energy: z.number().min(0).max(100),
    fatigue: z.number().min(0).max(100),
    stress: z.number().min(0).max(100),
    confidence: z.number().min(0).max(100),
    health: z.number().min(0).max(100),
    sleepHours: z.number().min(0).max(24),
  }),
});

const schoolSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(2),
  shortName: z.string().min(2),
  mascot: z.string().min(2),
  city: z.string().min(2),
  stateCode: z.string().length(2),
  primaryColor: z.string().min(4),
  secondaryColor: z.string().min(4),
  prestige: z.number().min(0).max(100),
  facilities: z.number().min(0).max(100),
  coaching: z.number().min(0).max(100),
  medicine: z.number().min(0).max(100),
  discipline: z.number().min(0).max(100),
  youthTrust: z.number().min(0).max(100),
  philosophy: z.string().min(2),
});


const playerYearSchema = z.enum(["Freshman", "Sophomore", "Junior", "Senior"]);
const rosterPositionSchema = z.enum(["QB", "RB", "WR", "TE", "OT", "OG", "C", "OL", "EDGE", "DT", "DL", "LB", "CB", "S", "K", "P"]);
const ecosystemRosterPositionSchema = z.enum(["QB", "RB", "WR", "TE", "OT", "OG", "C", "EDGE", "DT", "LB", "CB", "S", "K", "P"]);
const careerFootballPositionSchema = ecosystemRosterPositionSchema;
const coachSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(3),
  role: z.enum(["head-coach", "position-coach", "offensive-coordinator", "defensive-coordinator"]),
  age: z.number().int().min(25).max(80),
  archetype: z.enum(["builder", "disciplinarian", "strategist", "recruiter"]),
  development: z.number().min(0).max(100),
  tactics: z.number().min(0).max(100),
  discipline: z.number().min(0).max(100),
  communication: z.number().min(0).max(100),
  youthPatience: z.number().min(0).max(100),
  pressure: z.number().min(0).max(100),
  relationship: z.number().min(0).max(100),
  summary: z.string().min(2),
});
const rosterPlayerSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(3),
  position: rosterPositionSchema,
  unit: z.enum(["offense", "defense", "special"]),
  year: playerYearSchema,
  overall: z.number().min(0).max(100),
  potential: z.number().min(0).max(100),
  style: z.string().min(2),
  coachStanding: z.number().min(0).max(100),
  health: z.number().min(0).max(100),
  status: z.enum(["starter", "rotation", "backup", "injured"]),
  depthRank: z.number().int().min(1),
});
const depthEvaluationSchema = z.object({
  heroScore: z.number(),
  comparisonScore: z.number(),
  gap: z.number().min(0),
  trend: z.enum(["rising", "stable", "falling"]),
  summary: z.string().min(2),
  reasons: z.array(z.string().min(2)).min(1),
  updatedOn: z.string().min(8),
});
const depthDecisionSchema = z.object({
  type: z.enum(["promoted", "demoted", "held"]),
  title: z.string().min(2),
  description: z.string().min(2),
  occurredOn: z.string().min(8),
});

const trainingFocusSchema = z.enum(["position-craft", "explosive-power", "film-install", "recovery-reset"]);
const trainingIntensitySchema = z.enum(["controlled", "standard", "aggressive"]);
const activeHealthIssueSchema = z.object({
  id: z.string().min(1),
  diagnosis: z.string().min(2),
  area: z.enum(["lower-body", "upper-body", "head-neck", "back-core"]),
  severity: z.enum(["minor", "moderate"]),
  daysRemaining: z.number().int().nonnegative(),
  recurrenceRisk: z.number().min(0).max(100),
  startedOn: z.string().min(8),
});
const trainingSessionSchema = z.object({
  id: z.string().min(1),
  date: gameDateSchema,
  focusId: trainingFocusSchema,
  focusName: z.string().min(2),
  intensity: trainingIntensitySchema,
  grade: z.enum(["A", "B", "C", "D"]),
  load: z.number().min(0).max(100),
  readinessBefore: z.number().min(0).max(100),
  readinessAfter: z.number().min(0).max(100),
  sorenessDelta: z.number(),
  riskAfter: z.number().min(0).max(100),
  gains: z.object({
    technique: z.number(),
    athleticism: z.number(),
    footballIq: z.number(),
    competitiveness: z.number(),
  }),
  note: z.string().min(2),
  issueOccurred: z.string().min(2).optional(),
});
const footballTrainingSchema = z.object({
  moduleVersion: z.literal(1),
  plan: z.object({
    focusId: trainingFocusSchema,
    intensity: trainingIntensitySchema,
    revision: z.number().int().min(1),
  }),
  body: z.object({
    readiness: z.number().min(0).max(100),
    acuteLoad: z.number().min(0).max(100),
    chronicLoad: z.number().min(0).max(100),
    soreness: z.number().min(0).max(100),
    pain: z.number().min(0).max(100),
    injuryRisk: z.number().min(0).max(100),
    medicalStatus: z.enum(["cleared", "questionable", "limited", "out"]),
    restriction: z.string().min(2),
    activeIssue: activeHealthIssueSchema.optional(),
  }),
  momentum: z.object({
    technique: z.number().min(0).max(100),
    athleticism: z.number().min(0).max(100),
    footballIq: z.number().min(0).max(100),
    competitiveness: z.number().min(0).max(100),
  }),
  lastSession: trainingSessionSchema.optional(),
});


const matchStatLineSchema = z.object({
  passingAttempts: z.number().int().nonnegative(),
  completions: z.number().int().nonnegative(),
  passingYards: z.number().int(),
  rushingAttempts: z.number().int().nonnegative(),
  rushingYards: z.number().int(),
  targets: z.number().int().nonnegative(),
  receptions: z.number().int().nonnegative(),
  receivingYards: z.number().int(),
  touchdowns: z.number().int().nonnegative(),
  turnovers: z.number().int().nonnegative(),
  tackles: z.number().int().nonnegative(),
  tacklesForLoss: z.number().int().nonnegative(),
  sacks: z.number().int().nonnegative(),
  passBreakups: z.number().int().nonnegative(),
  interceptions: z.number().int().nonnegative(),
  sacksAllowed: z.number().int().nonnegative().default(0),
  pressuresAllowed: z.number().int().nonnegative().default(0),
  pancakes: z.number().int().nonnegative().default(0),
  hurries: z.number().int().nonnegative().default(0),
  runStops: z.number().int().nonnegative().default(0),
  coverageSnaps: z.number().int().nonnegative().default(0),
  fieldGoalsAttempted: z.number().int().nonnegative().default(0),
  fieldGoalsMade: z.number().int().nonnegative().default(0),
  longestFieldGoal: z.number().int().nonnegative().default(0),
  punts: z.number().int().nonnegative().default(0),
  puntYards: z.number().int().nonnegative().default(0),
  puntsInside20: z.number().int().nonnegative().default(0),
  returnYardsAllowed: z.number().int().nonnegative().default(0),
});

const collegeHeroGameStatLineSchema = matchStatLineSchema.extend({
  passingAttempts: z.number().int().nonnegative().default(0),
  completions: z.number().int().nonnegative().default(0),
  rushingAttempts: z.number().int().nonnegative().default(0),
  targets: z.number().int().nonnegative().default(0),
  receptions: z.number().int().nonnegative().default(0),
  tacklesForLoss: z.number().int().nonnegative().default(0),
  passBreakups: z.number().int().nonnegative().default(0),
});

const matchAdvancedStatLineSchema = z.object({
  snaps: z.number().int().nonnegative(),
  assignmentWins: z.number().int().nonnegative(),
  assignmentLosses: z.number().int().nonnegative(),
  routeWins: z.number().int().nonnegative(),
  separationWins: z.number().int().nonnegative(),
  blocksWon: z.number().int().nonnegative(),
  pressures: z.number().int().nonnegative(),
  coverageWins: z.number().int().nonnegative(),
  missedTackles: z.number().int().nonnegative(),
  passProtectionWins: z.number().int().nonnegative().default(0),
  runBlockWins: z.number().int().nonnegative().default(0),
  doubleTeamWins: z.number().int().nonnegative().default(0),
  kickQuality: z.number().int().nonnegative().default(0),
  puntQuality: z.number().int().nonnegative().default(0),
});

const emptyAdvancedMatchStats = {
  snaps: 0,
  assignmentWins: 0,
  assignmentLosses: 0,
  routeWins: 0,
  separationWins: 0,
  blocksWon: 0,
  pressures: 0,
  coverageWins: 0,
  missedTackles: 0,
  passProtectionWins: 0,
  runBlockWins: 0,
  doubleTeamWins: 0,
  kickQuality: 0,
  puntQuality: 0,
} as const;


const matchUsageRoleSchema = z.enum([
  "field-general",
  "lead-runner",
  "receiving-back",
  "deep-threat",
  "slot-option",
  "possession-target",
  "red-zone-target",
  "foundation-blocker",
  "disruptor",
  "second-level-anchor",
  "coverage-leader",
  "specialist",
]);

const matchUsagePlanSchema = z.object({
  role: matchUsageRoleSchema,
  label: z.string().min(1),
  targetPriority: z.number().min(0).max(100),
  touchPriority: z.number().min(0).max(100),
  redZonePriority: z.number().min(0).max(100),
  deepPriority: z.number().min(0).max(100),
  designedShare: z.number().min(0).max(100),
  shadowRisk: z.number().min(0).max(100),
  doubleTeamRisk: z.number().min(0).max(100),
});

const emptyMatchUsageStats = {
  routesRun: 0,
  openWindows: 0,
  targetsWhenOpen: 0,
  missedOpenWindows: 0,
  designedTouches: 0,
  actualTouches: 0,
  separationTotal: 0,
  separationSamples: 0,
} as const;

const matchUsageStatLineSchema = z.object({
  routesRun: z.number().int().nonnegative(),
  openWindows: z.number().int().nonnegative(),
  targetsWhenOpen: z.number().int().nonnegative(),
  missedOpenWindows: z.number().int().nonnegative(),
  designedTouches: z.number().int().nonnegative(),
  actualTouches: z.number().int().nonnegative(),
  separationTotal: z.number().nonnegative(),
  separationSamples: z.number().int().nonnegative(),
});

const matchDecisionOptionSchema = z.object({
  id: z.string().min(1),
  label: z.string().min(2),
  detail: z.string().min(2),
  risk: z.enum(["safe", "balanced", "aggressive"]),
  focus: z.enum(["technique", "athleticism", "football-iq", "competitiveness"]),
  difficulty: z.number().min(0).max(100),
  upside: z.number().min(0).max(100),
  mistakeRisk: z.number().min(0).max(100),
});

const matchPlayCallSchema = z.object({
  id: z.string().min(1).default("legacy-call"),
  formation: z.string().min(2),
  personnel: z.string().min(1),
  concept: z.string().min(2),
  playType: z.enum(["run", "pass", "play-action", "screen", "blitz", "coverage", "field-goal", "punt"]),
  strength: z.enum(["left", "right", "middle"]),
  calledBy: z.enum(["head-coach", "offensive-coordinator", "defensive-coordinator"]),
  canCheck: z.boolean(),
  aggression: z.number().min(0).max(100).default(50),
  primarySlot: z.string().min(1).optional(),
  progression: z.array(z.string().min(1)).default([]),
  runLane: z.string().min(1).optional(),
  tags: z.array(z.string().min(1)).default([]),
});

const matchPointSchema = z.object({
  x: z.number().min(0).max(100),
  y: z.number().min(0).max(100),
});

const matchPlayerAssignmentSchema = z.object({
  id: z.string().min(1),
  side: z.enum(["hero", "opponent"]),
  unit: z.enum(["offense", "defense", "special"]),
  slot: z.string().min(1),
  position: z.string().min(1),
  label: z.string().min(1),
  isHero: z.boolean(),
  kind: z.enum(["handoff", "carry", "pass-read", "route", "run-block", "pass-protection", "rush", "run-fit", "zone-coverage", "man-coverage", "spy", "contain", "kick", "punt", "long-snap", "kick-protection", "return", "return-coverage"]),
  task: z.string().min(2),
  start: matchPointSchema,
  end: matchPointSchema,
  delayMs: z.number().int().nonnegative().max(5000),
  matchupSlot: z.string().min(1).optional(),
  playerId: z.string().min(1).optional(),
  playerName: z.string().min(2).optional(),
  overall: z.number().min(0).max(100).optional(),
  health: z.number().min(0).max(100).optional(),
  depthRank: z.number().int().min(1).optional(),
});

const legacyPlayCall = {
  id: "legacy-call",
  formation: "Legacy",
  personnel: "11",
  concept: "Legacy Call",
  playType: "pass" as const,
  strength: "middle" as const,
  calledBy: "offensive-coordinator" as const,
  canCheck: false,
  aggression: 50,
  progression: [],
  tags: [],
};

const legacyOpponentCall = {
  ...legacyPlayCall,
  id: "legacy-defense",
  formation: "Legacy Front",
  concept: "Legacy Coverage",
  playType: "coverage" as const,
  calledBy: "defensive-coordinator" as const,
};

const matchEpisodeSchema = z.object({
  id: z.string().min(1),
  driveId: z.string().min(1).default("legacy-drive"),
  possession: z.enum(["hero", "opponent"]).default("hero"),
  unit: z.enum(["offense", "defense", "special"]),
  position: careerFootballPositionSchema,
  quarter: z.union([z.literal(1), z.literal(2), z.literal(3), z.literal(4)]),
  clockSeconds: z.number().int().min(0).max(900),
  playClockSeconds: z.number().int().min(0).max(40).default(25),
  down: z.union([z.literal(1), z.literal(2), z.literal(3), z.literal(4)]),
  distance: z.number().int().min(1).max(99),
  fieldPosition: z.number().int().min(0).max(100),
  scoreMargin: z.number().int(),
  title: z.string().min(2),
  situation: z.string().min(2),
  assignment: z.string().min(2),
  read: z.string().min(2),
  playCall: matchPlayCallSchema.default(legacyPlayCall),
  opponentCall: matchPlayCallSchema.default(legacyOpponentCall),
  heroInvolvement: z.enum(["primary", "secondary", "assignment-only"]).default("primary"),
  heroActive: z.boolean().default(true),
  heroRole: z.string().min(2).default("Выполнить назначение"),
  heroSlot: z.string().min(1).default("HERO"),
  receiverPriorities: z.record(z.string(), z.number().min(0).max(100)).optional(),
  heroUsageRole: matchUsageRoleSchema.optional(),
  assignments: z.array(matchPlayerAssignmentSchema).default([]),
  options: z.array(matchDecisionOptionSchema).min(3).max(4),
});

const matchEvaluationCriterionSchema = z.object({
  id: z.string().min(1),
  label: z.string().min(1),
  category: z.enum(["assignment", "technique", "decision", "execution", "impact", "discipline"]),
  score: z.number().min(0).max(100),
  weight: z.number().positive(),
  delta: z.number(),
  detail: z.string().min(1),
});

const matchSnapEvaluationSchema = z.object({
  score: z.number().min(0).max(100),
  grade: z.enum(["A", "B", "C", "D"]),
  summary: z.string().min(1),
  criteria: z.array(matchEvaluationCriterionSchema),
  strengths: z.array(z.string()),
  corrections: z.array(z.string()),
});

const matchGameEvaluationSchema = z.object({
  score: z.number().min(0).max(100),
  grade: z.enum(["A", "B", "C", "D"]),
  snapCount: z.number().int().nonnegative(),
  roleLabel: z.string().min(1),
  criteria: z.array(matchEvaluationCriterionSchema),
  bestSnapIds: z.array(z.string()),
  worstSnapIds: z.array(z.string()),
  summary: z.string().min(1),
});

const matchEpisodeResultSchema = z.object({
  id: z.string().min(1),
  episodeId: z.string().min(1),
  driveId: z.string().min(1).default("legacy-drive"),
  optionId: z.string().min(1),
  grade: z.enum(["A", "B", "C", "D"]),
  snapResult: z.enum(["run", "completion", "incomplete", "sack", "turnover", "touchdown", "defensive-touchdown", "penalty", "punt", "field-goal", "missed-field-goal", "turnover-on-downs"]).default("run"),
  headline: z.string().min(2),
  description: z.string().min(2),
  yards: z.number().int(),
  points: z.number().int().nonnegative(),
  scoringSide: z.enum(["hero", "opponent"]).optional(),
  coachDelta: z.number(),
  confidenceDelta: z.number(),
  fatigueDelta: z.number(),
  assignmentScore: z.number().min(0).max(100).default(50),
  teamExecutionScore: z.number().min(0).max(100).default(50),
  involved: z.boolean().default(true),
  firstDown: z.boolean().default(false),
  driveEnded: z.boolean().default(false),
  startFieldPosition: z.number().int().min(0).max(100).default(25),
  endFieldPosition: z.number().int().min(0).max(100).default(25),
  pressureOccurred: z.boolean().default(false),
  grossPuntYards: z.number().int().nonnegative().optional(),
  puntReturnYards: z.number().int().nonnegative().optional(),
  kickDistance: z.number().int().nonnegative().optional(),
  targetSlot: z.string().min(1).optional(),
  ballCarrierSlot: z.string().min(1).optional(),
  statDelta: matchStatLineSchema,
  advancedDelta: matchAdvancedStatLineSchema.default(emptyAdvancedMatchStats),
  evaluation: matchSnapEvaluationSchema.optional(),
});

const matchDriveSummarySchema = z.object({
  id: z.string().min(1),
  offense: z.enum(["hero", "opponent"]),
  startQuarter: z.union([z.literal(1), z.literal(2), z.literal(3), z.literal(4)]),
  startClockSeconds: z.number().int().min(0).max(900),
  endQuarter: z.union([z.literal(1), z.literal(2), z.literal(3), z.literal(4)]),
  endClockSeconds: z.number().int().min(0).max(900),
  startFieldPosition: z.number().int().min(0).max(100),
  endFieldPosition: z.number().int().min(0).max(100),
  plays: z.number().int().nonnegative(),
  yards: z.number().int(),
  points: z.number().int().nonnegative(),
  outcome: z.enum(["active", "touchdown", "defensive-touchdown", "field-goal", "missed-field-goal", "punt", "turnover", "turnover-on-downs", "end-half", "end-game"]),
  description: z.string().min(2),
  controlled: z.boolean(),
});


const matchTacticalCallSchema = z.object({
  id: z.string().min(1),
  concept: z.string().min(1),
  playType: z.enum(["run", "pass", "play-action", "screen", "blitz", "coverage", "field-goal", "punt"]),
  tags: z.array(z.string()),
  yards: z.number().int(),
  success: z.boolean(),
});

const matchTacticalMemorySchema = z.object({
  heroOffense: z.array(matchTacticalCallSchema).default([]),
  opponentOffense: z.array(matchTacticalCallSchema).default([]),
});

const footballMatchSchema = z.object({
  moduleVersion: z.literal(1),
  gameId: z.string().min(1),
  status: z.enum(["upcoming", "in-progress", "complete"]),
  scheduledWeek: z.number().int().min(1),
  scheduledDate: gameDateSchema,
  opponentId: z.string().min(1),
  opponentName: z.string().min(2),
  opponentRecord: z.string().min(1),
  opponentThreat: z.string().min(2),
  heroUnit: z.enum(["offense", "defense", "special"]),
  heroScore: z.number().int().nonnegative(),
  opponentScore: z.number().int().nonnegative(),
  quarter: z.union([z.literal(1), z.literal(2), z.literal(3), z.literal(4)]),
  clockSeconds: z.number().int().min(0).max(900),
  gameClockSeconds: z.number().int().min(0).max(3600).default(48 * 60),
  playClockSeconds: z.number().int().min(0).max(40).default(25),
  possession: z.enum(["hero", "opponent"]).default("hero"),
  openingKickoffReceiver: z.enum(["hero", "opponent"]).default("hero"),
  participationMode: z.enum(["auto", "key-moments", "every-snap"]).default("key-moments"),
  analysisMode: z.boolean().default(false),
  heroFatigue: z.number().min(0).max(100),
  coachGrade: z.number().min(0).max(100),
  episodeIndex: z.number().int().nonnegative(),
  totalEpisodes: z.number().int().min(1),
  rosterRole: z.enum(["starter", "rotation", "special-teams", "inactive", "practice-squad", "free-agent"]).optional(),
  entryQuarter: z.union([z.literal(1), z.literal(2), z.literal(3), z.literal(4)]).optional(),
  benchSummary: z.string().min(1).optional(),
  driveDown: z.union([z.literal(1), z.literal(2), z.literal(3), z.literal(4)]).default(1),
  driveDistance: z.number().int().min(1).max(99).default(10),
  driveFieldPosition: z.number().int().min(0).max(100).default(25),
  driveNumber: z.number().int().min(1).default(1),
  currentDriveId: z.string().min(1).default("legacy-drive"),
  driveStartQuarter: z.union([z.literal(1), z.literal(2), z.literal(3), z.literal(4)]).default(1),
  driveStartClockSeconds: z.number().int().min(0).max(900).default(720),
  driveStartFieldPosition: z.number().int().min(0).max(100).default(25),
  drivePlays: z.number().int().nonnegative().default(0),
  driveYards: z.number().int().default(0),
  timeoutsHero: z.number().int().min(0).max(3).default(3),
  timeoutsOpponent: z.number().int().min(0).max(3).default(3),
  tacticalMemory: matchTacticalMemorySchema.default({ heroOffense: [], opponentOffense: [] }),
  usagePlan: matchUsagePlanSchema.default({ role: "possession-target", label: "POSSESSION", targetPriority: 64, touchPriority: 58, redZonePriority: 58, deepPriority: 58, designedShare: 18, shadowRisk: 30, doubleTeamRisk: 12 }),
  usageStats: matchUsageStatLineSchema.default(emptyMatchUsageStats),
  currentEpisode: matchEpisodeSchema.optional(),
  lastResolvedEpisode: matchEpisodeSchema.optional(),
  lastResolvedResult: matchEpisodeResultSchema.optional(),
  completedEpisodes: z.array(matchEpisodeResultSchema),
  drives: z.array(matchDriveSummarySchema).default([]),
  stats: matchStatLineSchema,
  advancedStats: matchAdvancedStatLineSchema.default(emptyAdvancedMatchStats),
  finalResult: z.object({
    won: z.boolean(),
    heroScore: z.number().int().nonnegative(),
    opponentScore: z.number().int().nonnegative(),
    grade: z.enum(["A", "B", "C", "D"]),
    headline: z.string().min(2),
    summary: z.string().min(2),
    spotlight: z.string().min(2),
    coachTrustDelta: z.number(),
    visibilityDelta: z.number(),
    score: z.number().min(0).max(100).optional(),
    evaluation: matchGameEvaluationSchema.optional(),
    usage: matchUsageStatLineSchema.optional(),
  }).optional(),
});

const recruitingProgramTierSchema = z.enum(["national", "power", "regional", "developmental"]);
const recruitingStageSchema = z.enum(["unaware", "watchlist", "evaluating", "contact", "priority", "offered", "cooled"]);
const projectedCollegeRoleSchema = z.enum(["immediate-competition", "rotation-path", "developmental", "long-shot"]);
const recruitingProgramSchema = z.object({
  id: z.string().min(1),
  seed: z.string().min(1),
  name: z.string().min(2),
  shortName: z.string().min(2),
  city: z.string().min(2),
  stateCode: z.string().length(2),
  distanceMiles: z.number().int().nonnegative(),
  tier: recruitingProgramTierSchema,
  prestige: z.number().min(0).max(100),
  conferenceLevel: z.number().min(0).max(100),
  scheme: z.string().min(2),
  academicStandard: z.number().min(0).max(100),
  medicine: z.number().min(0).max(100),
  facilities: z.number().min(0).max(100),
  youthOpportunity: z.number().min(0).max(100),
  positionNeed: z.number().min(0).max(100),
  depthCompetition: z.number().min(0).max(100),
  fit: z.number().min(0).max(100),
  interest: z.number().min(0).max(100),
  scoutingConfidence: z.number().min(0).max(100),
  stage: recruitingStageSchema,
  academicEligible: z.boolean(),
  medicalConcern: z.boolean(),
  projectedRole: projectedCollegeRoleSchema,
  recruiterName: z.string().min(2),
  recruiterStyle: z.enum(["direct", "patient", "salesman", "analytical"]),
  contactQuality: z.number().min(0).max(100),
  roleClarity: z.number().min(0).max(100),
  staffTrust: z.number().min(0).max(100),
  visitStatus: z.enum(["none", "invited", "scheduled", "completed"]),
  officialVisit: z.object({
    id: z.string().min(1),
    status: z.enum(["scheduled", "completed"]),
    scheduledWeek: z.number().int().nonnegative(),
    scheduledDate: gameDateSchema,
    dueCompletedDay: z.number().int().nonnegative(),
    completedWeek: z.number().int().nonnegative().optional(),
    completedDate: gameDateSchema.optional(),
    campusFit: z.number().min(0).max(100).optional(),
    staffConnection: z.number().min(0).max(100).optional(),
    roleClarity: z.number().min(0).max(100).optional(),
    familyComfort: z.number().min(0).max(100).optional(),
    overallImpression: z.number().min(0).max(100).optional(),
    summary: z.string().min(2).optional(),
    warning: z.string().min(2).optional(),
  }).optional(),
  promises: z.array(z.object({
    id: z.string().min(1),
    category: z.enum(["role", "development", "scheme", "stability"]),
    statement: z.string().min(2),
    credibility: z.number().min(0).max(100),
    source: z.enum(["recruiter-call", "official-visit"]),
    madeWeek: z.number().int().nonnegative(),
  })),
  playerRead: z.string().min(2),
  evaluation: z.string().min(2),
  lastUpdate: z.string().min(2),
  offer: z.object({
    id: z.string().min(1),
    issuedWeek: z.number().int().nonnegative(),
    scholarship: z.literal("full"),
    projectedRole: projectedCollegeRoleSchema,
    expiresAfterWeek: z.number().int().min(1),
  }).optional(),
});
const footballRecruitingSchema = z.object({
  moduleVersion: z.literal(2),
  visibility: z.number().min(0).max(100),
  filmGrade: z.number().min(0).max(100),
  consistency: z.number().min(0).max(100),
  healthConfidence: z.number().min(0).max(100),
  academicClearance: z.number().min(0).max(100),
  coachRecommendation: z.number().min(0).max(100),
  competitionLevel: z.number().min(0).max(100),
  regionalRankLabel: z.string().min(2),
  interestedPrograms: z.number().int().nonnegative(),
  offers: z.number().int().nonnegative(),
  actionWeek: z.number().int().nonnegative(),
  actionsUsed: z.number().int().nonnegative().max(2),
  decommitments: z.number().int().nonnegative(),
  commitment: z.object({
    programId: z.string().min(1),
    status: z.enum(["verbal", "signed"]),
    committedWeek: z.number().int().nonnegative(),
    committedDate: gameDateSchema,
    confidence: z.number().min(0).max(100),
    signedDate: gameDateSchema.optional(),
    entryRoute: z.enum(["scholarship", "preferred-walk-on"]).optional(),
  }).optional(),
  programs: z.array(recruitingProgramSchema).min(20),
  activity: z.array(z.object({
    id: z.string().min(1),
    week: z.number().int().nonnegative(),
    programId: z.string().min(1).optional(),
    date: gameDateSchema,
    kind: z.enum(["evaluation", "contact", "action", "offer", "cooling", "conversation", "visit", "commitment", "signing", "expiration"]),
    title: z.string().min(2),
    detail: z.string().min(2),
  })),
});


const collegeHeroRoleSchema = z.enum(["starter", "rotation", "special-teams", "developmental"]);
const collegePlayerYearSchema = z.enum(["Freshman", "Sophomore", "Junior", "Senior"]);
const collegeHeroDecisionSchema = z.object({
  id: z.string().min(1),
  kind: z.enum(["coach-meeting", "position-rivalry", "transfer-window", "transfer-destination"]),
  createdWeek: z.number().int().min(1),
  title: z.string().min(2),
  detail: z.string().min(2),
  options: z.array(z.object({
    id: z.string().min(1),
    label: z.string().min(2),
    detail: z.string().min(2),
  })).min(2),
});
const collegeHeroCareerSchema = z.object({
  version: z.literal(2),
  status: z.enum(["active", "complete"]),
  teamId: z.string().min(1),
  seasonYear: z.number().int(),
  classYear: collegePlayerYearSchema,
  eligibilityYears: z.number().int().min(0).max(6),
  week: z.number().int().min(1),
  role: collegeHeroRoleSchema,
  depthRank: z.number().int().min(1),
  coachTrust: z.number().min(0).max(100),
  lockerRoomStanding: z.number().min(0).max(100),
  practiceReps: z.number().min(0).max(100),
  weeklyPracticeGrade: z.enum(["A", "B", "C", "D"]),
  seasonSnaps: z.number().int().nonnegative(),
  gamesPlayed: z.number().int().nonnegative(),
  starts: z.number().int().nonnegative(),
  careerSnaps: z.number().int().nonnegative(),
  careerGames: z.number().int().nonnegative(),
  careerStarts: z.number().int().nonnegative(),
  seasonOverallStart: z.number().min(0).max(100),
  redshirtStatus: z.enum(["active", "candidate", "used"]),
  transferIntent: z.enum(["stay", "open", "portal"]),
  transferOffers: z.array(z.object({
    teamId: z.string().min(1),
    teamName: z.string().min(2),
    shortName: z.string().min(1),
    projectedRole: collegeHeroRoleSchema,
    schemeFit: z.number().min(0).max(100),
    scholarship: z.boolean(),
    summary: z.string().min(2),
  })),
  promises: z.array(z.object({
    id: z.string().min(1),
    kind: z.literal("playing-time"),
    targetRole: projectedCollegeRoleSchema,
    madeWeek: z.number().int().min(1),
    deadlineWeek: z.number().int().min(1),
    status: z.enum(["active", "kept", "broken"]),
    summary: z.string().min(2),
  })),
  pendingDecision: collegeHeroDecisionSchema.optional(),
  gameLog: z.array(z.object({
    id: z.string().min(1),
    seasonYear: z.number().int(),
    week: z.number().int().min(1),
    opponentId: z.string().min(1),
    opponentName: z.string().min(1),
    won: z.boolean(),
    score: z.string().min(3),
    snaps: z.number().int().nonnegative(),
    started: z.boolean(),
    grade: z.enum(["A", "B", "C", "D"]),
    role: collegeHeroRoleSchema,
    spotlight: z.string().min(1).optional(),
    stats: collegeHeroGameStatLineSchema.optional(),
    usage: matchUsageStatLineSchema.optional(),
  })),
  weekLog: z.array(z.object({
    id: z.string().min(1),
    seasonYear: z.number().int(),
    week: z.number().int().min(1),
    role: collegeHeroRoleSchema,
    depthRank: z.number().int().min(1),
    coachTrust: z.number().min(0).max(100),
    lockerRoomStanding: z.number().min(0).max(100),
    practiceGrade: z.enum(["A", "B", "C", "D"]),
    summary: z.string().min(2),
  })),
  seasonHistory: z.array(z.object({
    seasonYear: z.number().int(),
    classYear: collegePlayerYearSchema,
    teamId: z.string().min(1),
    teamName: z.string().min(1),
    wins: z.number().int().nonnegative(),
    losses: z.number().int().nonnegative(),
    role: collegeHeroRoleSchema,
    gamesPlayed: z.number().int().nonnegative(),
    starts: z.number().int().nonnegative(),
    snaps: z.number().int().nonnegative(),
    averageGrade: z.enum(["A", "B", "C", "D"]),
    redshirted: z.boolean(),
    overallStart: z.number().min(0).max(100),
    overallEnd: z.number().min(0).max(100),
    coachTrustEnd: z.number().min(0).max(100),
    awards: z.array(z.string().min(1)),
  })),
  lastSummary: z.string().min(2),
});

const footballCollegeSchema = z.object({
  moduleVersion: z.literal(1),
  status: z.enum(["high-school", "signed", "orientation", "active"]),
  entryRoute: z.enum(["scholarship", "preferred-walk-on"]).optional(),
  signedProgramId: z.string().min(1).optional(),
  signedDate: gameDateSchema.optional(),
  program: z.object({
    id: z.string().min(1),
    name: z.string().min(2),
    shortName: z.string().min(2),
    city: z.string().min(2),
    stateCode: z.string().length(2),
    tier: recruitingProgramTierSchema,
    prestige: z.number().min(0).max(100),
    scheme: z.string().min(2),
    medicine: z.number().min(0).max(100),
    facilities: z.number().min(0).max(100),
    youthOpportunity: z.number().min(0).max(100),
    headCoachName: z.string().min(2),
    recruiterName: z.string().min(2),
  }).optional(),
  positionRoom: z.array(z.object({
    id: z.string().min(1),
    name: z.string().min(2),
    year: z.enum(["Freshman", "Sophomore", "Junior", "Senior"]),
    overall: z.number().min(0).max(100),
    style: z.string().min(2),
    redshirt: z.boolean(),
    depthRank: z.number().int().nonnegative(),
    isHero: z.boolean(),
  })),
  depthRank: z.number().int().min(1).optional(),
  projectedRole: projectedCollegeRoleSchema.optional(),
  actualRole: projectedCollegeRoleSchema.optional(),
  promiseVerdict: z.enum(["kept", "uncertain", "misleading"]).optional(),
  promiseSummary: z.string().min(2).optional(),
  offseason: z.object({
    startDate: gameDateSchema,
    arrivalDate: gameDateSchema,
    trainingGrade: z.enum(["A", "B", "C", "D"]),
    overallDelta: z.number(),
    weightDelta: z.number(),
    gpaDelta: z.number(),
    healthDelta: z.number(),
    confidenceDelta: z.number(),
    summary: z.string().min(2),
  }).optional(),
  arrivalDate: gameDateSchema.optional(),
  onboardingPriority: z.enum(["compete-now", "learn-system", "academic-base"]).optional(),
  heroCareer: collegeHeroCareerSchema.optional(),
});


const professionalPositionNeedsSchema = z.object({
  QB: z.number().min(0).max(100), RB: z.number().min(0).max(100), WR: z.number().min(0).max(100),
  TE: z.number().min(0).max(100).default(55), OT: z.number().min(0).max(100).default(55), OG: z.number().min(0).max(100).default(55), C: z.number().min(0).max(100).default(55),
  EDGE: z.number().min(0).max(100).default(55), DT: z.number().min(0).max(100).default(55), LB: z.number().min(0).max(100), CB: z.number().min(0).max(100),
  S: z.number().min(0).max(100).default(55), K: z.number().min(0).max(100).default(45), P: z.number().min(0).max(100).default(45),
});

const professionalRosterPlayerSchema = z.object({
  id: z.string().min(1),
  sourcePlayerId: z.string().min(1).optional(),
  collegeTeamId: z.string().min(1).optional(),
  collegeName: z.string().min(1).optional(),
  draftYear: z.number().int().min(2020).max(2200).optional(),
  draftRound: z.number().int().min(1).max(7).nullable().optional(),
  draftPick: z.number().int().min(1).nullable().optional(),
  name: z.string().min(2),
  teamId: z.string().min(1).optional(),
  position: careerFootballPositionSchema,
  age: z.number().int().min(18).max(45),
  overall: z.number().min(0).max(100),
  potential: z.number().min(0).max(100),
  health: z.number().min(0).max(100),
  form: z.number().min(0).max(100),
  schemeFit: z.number().min(0).max(100).default(60),
  depthRank: z.number().int().nonnegative(),
  yearsRemaining: z.number().int().min(0).max(7),
  annualSalary: z.number().int().nonnegative(),
  guaranteedRemaining: z.number().int().nonnegative(),
  status: z.enum(["active", "practice-squad", "free-agent", "injured-reserve"]),
  availability: z.enum(["active", "questionable", "out", "injured-reserve"]).default("active"),
  injuryWeeks: z.number().int().min(0).max(52).default(0),
  isHero: z.boolean(),
});

const professionalGameSchema = z.object({
  id: z.string().min(1),
  seasonYear: z.number().int().min(2020).max(2200),
  week: z.number().int().min(1).max(30),
  date: gameDateSchema,
  homeTeamId: z.string().min(1),
  awayTeamId: z.string().min(1),
  status: z.enum(["scheduled", "complete"]),
  homeScore: z.number().int().nonnegative().optional(),
  awayScore: z.number().int().nonnegative().optional(),
  playoffRound: z.enum(["wild-card", "conference", "championship"]).optional(),
});

const professionalMatchStatsSchema = z.object({
  passingAttempts: z.number().int().nonnegative(), completions: z.number().int().nonnegative(), passingYards: z.number().int(),
  rushingAttempts: z.number().int().nonnegative(), rushingYards: z.number().int(), targets: z.number().int().nonnegative(), receptions: z.number().int().nonnegative(), receivingYards: z.number().int(),
  touchdowns: z.number().int().nonnegative(), turnovers: z.number().int().nonnegative(), tackles: z.number().int().nonnegative(), tacklesForLoss: z.number().int().nonnegative(), sacks: z.number().int().nonnegative(),
  passBreakups: z.number().int().nonnegative(), interceptions: z.number().int().nonnegative(), sacksAllowed: z.number().int().nonnegative(), pressuresAllowed: z.number().int().nonnegative(), pancakes: z.number().int().nonnegative(),
  hurries: z.number().int().nonnegative(), runStops: z.number().int().nonnegative(), coverageSnaps: z.number().int().nonnegative(), fieldGoalsAttempted: z.number().int().nonnegative(), fieldGoalsMade: z.number().int().nonnegative(),
  longestFieldGoal: z.number().int().nonnegative(), punts: z.number().int().nonnegative(), puntYards: z.number().int(), puntsInside20: z.number().int().nonnegative(), returnYardsAllowed: z.number().int().nonnegative(),
});


const professionalCoachSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(2),
  role: z.enum(["head-coach", "offensive-coordinator", "defensive-coordinator", "position-coach"]),
  age: z.number().int().min(25).max(80),
  reputation: z.number().min(0).max(100),
  tactics: z.number().min(0).max(100),
  development: z.number().min(0).max(100),
  adaptability: z.number().min(0).max(100),
  gameManagement: z.number().min(0).max(100),
  jobSecurity: z.number().min(0).max(100),
  contractYears: z.number().int().min(0).max(10),
  annualSalary: z.number().int().nonnegative(),
  offenseSystem: z.enum(["air-raid", "west-coast", "power-run", "spread-option", "multiple"]),
  defenseSystem: z.enum(["quarters-425", "multiple-34", "over-43", "nickel-match", "man-pressure", "multiple-defense"]),
});

const professionalTacticalSchema = z.object({
  offenseSystem: z.enum(["air-raid", "west-coast", "power-run", "spread-option", "multiple"]),
  defenseSystem: z.enum(["quarters-425", "multiple-34", "over-43", "nickel-match", "man-pressure", "multiple-defense"]),
  tempo: z.enum(["controlled", "balanced", "fast"]),
  offensiveAggression: z.enum(["conservative", "balanced", "aggressive"]),
  defensiveAggression: z.enum(["conservative", "balanced", "aggressive"]),
  runRate: z.number().min(0).max(100),
  playActionRate: z.number().min(0).max(100),
  screenRate: z.number().min(0).max(100),
  deepShotRate: z.number().min(0).max(100),
  blitzRate: z.number().min(0).max(100),
  manCoverageRate: z.number().min(0).max(100),
  disguiseRate: z.number().min(0).max(100),
  fourthDownAggression: z.number().min(0).max(100),
  adaptation: z.number().min(0).max(100),
});

const professionalStateSchema = z.object({
  version: z.literal(2),
  status: z.enum(["dormant", "decision", "agent-selection", "evaluation", "draft-ready", "drafted", "undrafted", "training-camp", "roster", "practice-squad", "free-agent", "cut"]),
  draftYear: z.number().int().min(2020).max(2200),
  declared: z.boolean(),
  draftStock: z.number().min(0).max(100),
  projectedRound: z.number().int().min(1).max(7).nullable(),
  projectedRange: z.string().min(2),
  agents: z.array(z.object({
    id: z.string().min(1), name: z.string().min(2), agency: z.string().min(2), reputation: z.number().min(0).max(100),
    negotiation: z.number().min(0).max(100), mediaReach: z.number().min(0).max(100), teamAccess: z.number().min(0).max(100),
    commission: z.number().min(0).max(25), risk: z.number().min(0).max(100), summary: z.string().min(2),
  })).min(3),
  selectedAgentId: z.string().min(1).optional(),
  teams: z.array(z.object({
    id: z.string().min(1), city: z.string().min(2), name: z.string().min(2), shortName: z.string().min(2), conference: z.enum(["AFC", "NFC"]),
    prestige: z.number().min(0).max(100), rosterStrength: z.number().min(0).max(100), wins: z.number().int().nonnegative(), losses: z.number().int().nonnegative(),
    salaryCap: z.number().int().positive(), payroll: z.number().int().nonnegative(), deadCap: z.number().int().nonnegative(), capSpace: z.number().int().nonnegative(), rosterSize: z.number().int().nonnegative(),
    needs: professionalPositionNeedsSchema,
    staff: z.array(professionalCoachSchema).optional(),
    tactical: professionalTacticalSchema.optional(),
  })).min(16),
  prospects: z.array(z.object({
    id: z.string().min(1), sourcePlayerId: z.string().min(1).optional(), collegeTeamId: z.string().min(1).optional(), previousTeamIds: z.array(z.string().min(1)).default([]), seasonsPlayed: z.number().int().nonnegative().default(0), declaredEarly: z.boolean().default(false), name: z.string().min(2), position: careerFootballPositionSchema, collegeName: z.string().min(1), age: z.number().int().min(18).max(30),
    overall: z.number().min(0).max(100), potential: z.number().min(0).max(100), production: z.number().min(0).max(100), athleticScore: z.number().min(0).max(100),
    medicalScore: z.number().min(0).max(100), interviewScore: z.number().min(0).max(100), draftGrade: z.number().min(0).max(100), projectedRound: z.number().int().min(1).max(7).nullable(), isHero: z.boolean(),
  })),
  draftOrder: z.array(z.object({ id: z.string().min(1), round: z.number().int().min(1).max(7), pickInRound: z.number().int().min(1), overallPick: z.number().int().min(1), originalTeamId: z.string().min(1), currentTeamId: z.string().min(1), traded: z.boolean() })),
  evaluation: z.object({
    completedOn: gameDateSchema, focus: z.enum(["athletic", "technical", "interview"]), fortyYard: z.number().min(3).max(7), shuttle: z.number().min(3).max(7), vertical: z.number().min(10).max(60),
    benchReps: z.number().int().min(0).max(60), positionDrill: z.number().min(0).max(100), medical: z.number().min(0).max(100), interview: z.number().min(0).max(100), overallScore: z.number().min(0).max(100), stockDelta: z.number().min(-30).max(30), summary: z.string().min(2),
  }).optional(),
  draftResults: z.array(z.object({ id: z.string().min(1), sourcePlayerId: z.string().min(1).optional(), round: z.number().int().min(1).max(7), pickInRound: z.number().int().min(1), overallPick: z.number().int().min(1), teamId: z.string().min(1), prospectId: z.string().min(1), prospectName: z.string().min(2), position: careerFootballPositionSchema, collegeName: z.string().min(1), grade: z.number().min(0).max(100), isHero: z.boolean() })),
  heroSelection: z.object({ id: z.string().min(1), sourcePlayerId: z.string().min(1).optional(), round: z.number().int().min(1).max(7), pickInRound: z.number().int().min(1), overallPick: z.number().int().min(1), teamId: z.string().min(1), prospectId: z.string().min(1), prospectName: z.string().min(2), position: careerFootballPositionSchema, collegeName: z.string().min(1), grade: z.number().min(0).max(100), isHero: z.boolean() }).optional(),
  campInvites: z.array(z.object({ teamId: z.string().min(1), teamName: z.string().min(2), shortName: z.string().min(2), signingBonus: z.number().int().nonnegative(), rosterOpportunity: z.number().min(0).max(100), positionCompetition: z.number().min(0).max(100), schemeFit: z.number().min(0).max(100), summary: z.string().min(2) })),
  contract: z.object({ teamId: z.string().min(1), teamName: z.string().min(2), years: z.number().int().min(1).max(7), totalValue: z.number().int().nonnegative(), guaranteed: z.number().int().nonnegative(), signingBonus: z.number().int().nonnegative(), salaryYearOne: z.number().int().nonnegative(), agentFee: z.number().int().nonnegative(), round: z.number().int().min(1).max(7).nullable(), overallPick: z.number().int().min(1).nullable() }).optional(),
  camp: z.object({
    teamId: z.string().min(1), day: z.number().int().min(1).max(10), totalDays: z.number().int().min(1).max(10), coachTrust: z.number().min(0).max(100), rosterRank: z.number().int().min(1), playersAtPosition: z.number().int().min(1),
    sessions: z.array(z.object({ id: z.string().min(1), day: z.number().int().min(1), approach: z.enum(["controlled", "balanced", "aggressive"]), grade: z.enum(["A", "B", "C", "D"]), performance: z.number().min(0).max(100), healthDelta: z.number(), coachTrustDelta: z.number(), summary: z.string().min(2) })),
    outcome: z.enum(["active-roster", "practice-squad", "released"]).optional(),
  }).optional(),
  league: z.object({
    seasonYear: z.number().int().min(2020).max(2200), phase: z.enum(["preseason", "regular-season", "playoffs", "complete"]), week: z.number().int().min(0).max(30), totalWeeks: z.number().int().min(1).max(30),
    schedule: z.array(professionalGameSchema), roster: z.array(professionalRosterPlayerSchema), freeAgents: z.array(professionalRosterPlayerSchema),
    transactions: z.array(z.object({ id: z.string().min(1), seasonYear: z.number().int(), week: z.number().int().nonnegative(), kind: z.enum(["signing", "release", "waiver-claim", "injury", "promotion", "trade", "cap-move"]), playerId: z.string().min(1), playerName: z.string().min(2), position: careerFootballPositionSchema, fromTeamId: z.string().min(1).optional(), toTeamId: z.string().min(1).optional(), value: z.number().int().nonnegative(), summary: z.string().min(2) })),
    playoffTeamIds: z.array(z.string().min(1)), championTeamId: z.string().min(1).optional(), activeGameId: z.string().min(1).optional(),
  }),
  heroCareer: z.object({
    teamId: z.string().min(1).optional(), seasonYear: z.number().int().min(2020).max(2200), week: z.number().int().min(1).max(30), role: z.enum(["starter", "rotation", "special-teams", "inactive", "practice-squad", "free-agent"]),
    depthRank: z.number().int().min(1), coachTrust: z.number().min(0).max(100), gamesPlayed: z.number().int().nonnegative(), starts: z.number().int().nonnegative(), snaps: z.number().int().nonnegative(),
    gameLog: z.array(z.object({ seasonYear: z.number().int().min(2020).max(2200), gameId: z.string().min(1), week: z.number().int().min(1), opponentId: z.string().min(1), won: z.boolean(), teamScore: z.number().int().nonnegative(), opponentScore: z.number().int().nonnegative(), grade: z.enum(["A", "B", "C", "D"]), performanceScore: z.number().min(0).max(100).optional(), evaluationSummary: z.string().min(1).optional(), criterionScores: z.array(z.object({ id: z.string().min(1), label: z.string().min(1), score: z.number().min(0).max(100) })).optional(), snaps: z.number().int().nonnegative(), stats: professionalMatchStatsSchema, usage: matchUsageStatLineSchema.optional() })),
    availability: z.enum(["active", "questionable", "out", "injured-reserve"]).default("active"),
    weeklyPlan: z.object({
      seasonYear: z.number().int().min(2020).max(2200), week: z.number().int().min(1).max(30), focus: z.enum(["playbook", "technique", "recovery", "competition"]), resolved: z.boolean(),
      readinessDelta: z.number(), coachTrustDelta: z.number(), healthDelta: z.number(), depthDelta: z.number(), injuryRisk: z.number().min(0).max(100), summary: z.string().min(2),
    }).default({ seasonYear: 2030, week: 1, focus: "playbook", resolved: false, readinessDelta: 0, coachTrustDelta: 0, healthDelta: 0, depthDelta: 0, injuryRisk: 0, summary: "План недели ещё не выбран." }),
  }).optional(),
  lastSummary: z.string().min(2),
});

const footballSchema = z.object({
  moduleVersion: z.literal(8),
  worldSeed: z.string().min(1),
  stage: z.enum(["high-school-preseason", "college-orientation", "college-season", "professional-draft", "professional-career"]),
  position: careerFootballPositionSchema,
  archetypeId: z.string().min(1),
  archetypeName: z.string().min(1),
  jerseyNumber: z.number().int().min(0).max(99),
  ratings: z.object({
    overall: z.number().min(0).max(100),
    potentialBand: z.enum(["role-player", "starter", "high-upside", "national-ceiling"]),
    athleticism: z.number().min(0).max(100),
    technique: z.number().min(0).max(100),
    footballIq: z.number().min(0).max(100),
    competitiveness: z.number().min(0).max(100),
  }),
  school: schoolSchema,
  staff: z.object({
    headCoach: coachSchema,
    positionCoach: coachSchema,
    offensiveCoordinator: coachSchema,
    defensiveCoordinator: coachSchema,
  }),
  roster: z.array(rosterPlayerSchema).min(35),
  teamDynamics: z.object({
    morale: z.number().min(0).max(100),
    cohesion: z.number().min(0).max(100),
    discipline: z.number().min(0).max(100),
    schemeMastery: z.number().min(0).max(100),
  }),
  training: footballTrainingSchema,
  match: footballMatchSchema,
  depthChart: z.object({
    rank: z.number().int().min(1),
    playersAtPosition: z.number().int().min(1),
    coachTrust: z.number().min(0).max(100),
    projectedRole: z.enum(["starter", "rotation", "special-teams", "developmental"]),
    directRival: z.object({
      id: z.string().min(1),
      name: z.string().min(3),
      year: playerYearSchema,
      overall: z.number().min(0).max(100),
      style: z.string().min(2),
    }),
    evaluation: depthEvaluationSchema,
    lastDecision: depthDecisionSchema,
  }),
  season: z.object({
    year: z.number().int().min(2000),
    phase: z.enum(["regular-season", "complete"]),
    week: z.number().int().nonnegative(),
    wins: z.number().int().nonnegative(),
    losses: z.number().int().nonnegative(),
    nextOpponent: z.object({
      id: z.string().min(1),
      name: z.string().min(2),
      record: z.string().min(1),
      threat: z.string().min(2),
    }),
    totalWeeks: z.number().int().min(1),
    opponents: z.array(z.object({
      id: z.string().min(1),
      name: z.string().min(2),
      shortName: z.string().min(1),
      mascot: z.string().min(2),
      city: z.string().min(2),
      stateCode: z.string().length(2),
      rating: z.number().min(0).max(100),
      offenseStyle: z.string().min(2),
      defenseStyle: z.string().min(2),
      strength: z.string().min(2),
      weakness: z.string().min(2),
      keyPlayer: z.string().min(2),
      scoutConfidence: z.number().min(0).max(100),
    })).min(1),
    schedule: z.array(z.object({
      id: z.string().min(1),
      week: z.number().int().min(1),
      date: gameDateSchema,
      home: z.boolean(),
      opponentId: z.string().min(1),
      opponentName: z.string().min(2),
      opponentShortName: z.string().min(1),
      opponentRating: z.number().min(0).max(100),
      status: z.enum(["scheduled", "complete"]),
      heroScore: z.number().int().nonnegative().optional(),
      opponentScore: z.number().int().nonnegative().optional(),
      won: z.boolean().optional(),
      heroGrade: z.enum(["A", "B", "C", "D"]).optional(),
      spotlight: z.string().min(2).optional(),
    })).min(1),
    standings: z.array(z.object({
      teamId: z.string().min(1),
      name: z.string().min(2),
      shortName: z.string().min(1),
      rating: z.number().min(0).max(100),
      wins: z.number().int().nonnegative(),
      losses: z.number().int().nonnegative(),
      pointsFor: z.number().int().nonnegative(),
      pointsAgainst: z.number().int().nonnegative(),
      streak: z.number().int(),
      isHeroTeam: z.boolean(),
    })).min(2),
    heroTotals: matchStatLineSchema,
    awards: z.array(z.object({
      id: z.string().min(1),
      week: z.number().int().min(1),
      title: z.string().min(2),
      playerName: z.string().min(2),
      teamName: z.string().min(1),
      detail: z.string().min(2),
      isHero: z.boolean(),
    })),
    teamLeaders: z.array(z.object({
      id: z.string().min(1),
      name: z.string().min(2),
      position: z.string().min(1),
      category: z.string().min(2),
      value: z.string().min(1),
    })),
  }),
  recruitment: footballRecruitingSchema,
  college: footballCollegeSchema,
  professional: professionalStateSchema,
});

const focusSchema = z.object({
  training: z.number().min(0).max(100),
  recovery: z.number().min(0).max(100),
  study: z.number().min(0).max(100),
  social: z.number().min(0).max(100),
});

const dayDeltaSchema = z.object({
  energy: z.number(),
  fatigue: z.number(),
  stress: z.number(),
  confidence: z.number(),
  health: z.number(),
  gpa: z.number(),
  coachTrust: z.number(),
  overall: z.number(),
});

const dayOutcomeSchema = z.object({
  id: z.string().min(1),
  date: gameDateSchema,
  grade: z.enum(["A", "B", "C", "D"]),
  title: z.string().min(1),
  summary: z.string().min(1),
  highlights: z.array(z.string().min(1)),
  deltas: dayDeltaSchema,
});

const lifeSchema = z.object({
  moduleVersion: z.literal(1),
  weekNumber: z.number().int().min(1),
  dayIndex: z.number().int().min(0).max(6),
  completedDays: z.number().int().nonnegative(),
  weeklyPlan: z.object({
    templateId: z.enum(["balanced", "breakout", "recovery", "academic", "film-room"]),
    intensity: z.enum(["controlled", "standard", "aggressive"]),
    focus: focusSchema,
    revision: z.number().int().min(1),
  }),
  consistency: z.number().min(0).max(100),
  lastOutcome: dayOutcomeSchema.optional(),
});


const relationshipMemorySchema = z.object({
  id: z.string().min(1),
  date: gameDateSchema,
  summary: z.string().min(2),
  impact: z.number().min(-100).max(100),
  importance: z.union([z.literal(1), z.literal(2), z.literal(3), z.literal(4), z.literal(5)]),
});

const relationshipNpcSchema = z.object({
  id: z.string().min(1),
  seed: z.string().min(1),
  linkedEntityId: z.string().min(1).optional(),
  name: z.string().min(2),
  age: z.number().int().min(14).max(90),
  role: z.enum(["guardian", "head-coach", "position-coach", "rival", "teammate", "counselor", "reporter"]),
  group: z.enum(["family", "team", "school", "media"]),
  relationship: z.number().min(-100).max(100),
  temperament: z.enum(["direct", "reserved", "volatile", "warm", "calculating", "demanding"]),
  goal: z.string().min(2),
  fear: z.string().min(2),
  currentSituation: z.string().min(2),
  status: z.enum(["steady", "under-pressure", "hopeful", "frustrated", "focused", "concerned"]),
  memories: z.array(relationshipMemorySchema),
});

const relationshipEffectSchema = z.object({
  relationship: z.number().min(-100).max(100),
  coachTrust: z.number().optional(),
  confidence: z.number().optional(),
  stress: z.number().optional(),
  energy: z.number().optional(),
  gpa: z.number().optional(),
  visibility: z.number().optional(),
  teamMorale: z.number().optional(),
});

const relationshipEventTypeSchema = z.enum([
  "coach-accountability",
  "coach-plan-review",
  "rival-pressure",
  "family-academics",
  "family-check-in",
  "teammate-film",
  "counselor-warning",
  "reporter-spotlight",
]);

const relationshipEventSchema = z.object({
  id: z.string().min(1),
  type: relationshipEventTypeSchema,
  createdOn: gameDateSchema,
  title: z.string().min(2),
  scene: z.string().min(2),
  context: z.array(z.string().min(2)).min(1),
  participantIds: z.array(z.string().min(1)).min(1),
  primaryNpcId: z.string().min(1),
  options: z.array(z.object({
    id: z.string().min(1),
    label: z.string().min(2),
    detail: z.string().min(2),
    tone: z.enum(["calm", "firm", "defensive", "open"]),
    effects: relationshipEffectSchema,
    memory: z.string().min(2),
    outcome: z.string().min(2),
    followUp: z.object({ type: relationshipEventTypeSchema, delayDays: z.number().int().min(1) }).optional(),
  })).min(2).max(4),
});

const relationshipsSchema = z.object({
  moduleVersion: z.literal(1),
  npcs: z.array(relationshipNpcSchema).min(4),
  pendingEvent: relationshipEventSchema.optional(),
  resolvedEvents: z.array(z.object({
    id: z.string().min(1),
    type: relationshipEventTypeSchema,
    title: z.string().min(2),
    resolvedOn: gameDateSchema,
    resolvedAtCompletedDay: z.number().int().nonnegative(),
    primaryNpcId: z.string().min(1),
    optionId: z.string().min(1),
    outcome: z.string().min(2),
    relationshipDelta: z.number().min(-100).max(100),
  })),
  queuedEvents: z.array(z.object({
    id: z.string().min(1),
    type: relationshipEventTypeSchema,
    dueCompletedDay: z.number().int().nonnegative(),
    primaryNpcId: z.string().min(1),
  })),
  lastGeneratedCompletedDay: z.number().int().min(-1),
});

const ecosystemPositionNeedsSchema = z.object({
  QB: z.number().min(0).max(100),
  RB: z.number().min(0).max(100),
  WR: z.number().min(0).max(100),
  TE: z.number().min(0).max(100),
  OT: z.number().min(0).max(100),
  OG: z.number().min(0).max(100),
  C: z.number().min(0).max(100),
  EDGE: z.number().min(0).max(100),
  DT: z.number().min(0).max(100),
  LB: z.number().min(0).max(100),
  CB: z.number().min(0).max(100),
  S: z.number().min(0).max(100),
  K: z.number().min(0).max(100),
  P: z.number().min(0).max(100),
});

const worldConstitutionSchema = z.object({
  version: z.literal(1),
  modernEligibilityStartYear: z.number().int().min(2020).max(2200),
  ageBasedEligibilityYears: z.number().int().min(1).max(10),
  legacyCompetitionSeasons: z.number().int().min(1).max(10),
  legacyEligibilityWindowYears: z.number().int().min(1).max(10),
  legacyRedshirtGameLimit: z.number().int().min(0).max(20),
  collegeRosterLimit: z.number().int().min(1).max(200),
  collegeScholarshipLimit: z.number().int().min(0).max(200),
  minimumTermCredits: z.number().min(0).max(30),
  degreeProgressBenchmarks: z.object({
    endOfYearTwo: z.number().min(0).max(100),
    endOfYearThree: z.number().min(0).max(100),
    endOfYearFour: z.number().min(0).max(100),
  }),
  simulationOrder: z.tuple([
    z.literal("calendar"),
    z.literal("eligibility"),
    z.literal("rosters"),
    z.literal("teams"),
    z.literal("competition"),
    z.literal("recruiting"),
    z.literal("movement"),
    z.literal("history"),
  ]),
});

const worldCycleSchema = z.object({
  academicYear: z.number().int().min(2020).max(2200),
  seasonYear: z.number().int().min(2020).max(2200),
  phase: z.enum(["summer-recruiting", "preseason", "regular-season", "postseason", "winter-evaluation", "spring-development"]),
  phaseWeek: z.number().int().min(1).max(30),
});

const ecosystemTeamComplianceSchema = z.object({
  rosterLimit: z.number().int().min(1).max(200),
  scholarshipLimit: z.number().int().min(0).max(200),
  fundedScholarships: z.number().int().min(0).max(200),
  estimatedRosterSize: z.number().int().min(0).max(200),
  scholarshipsUsed: z.number().int().min(0).max(200),
  academicSupport: z.number().min(0).max(100),
  status: z.enum(["clear", "warning", "violation"]),
});

const ecosystemProgramResourcesSchema = z.object({
  tier: z.enum(["local", "regional", "power", "elite"]),
  annualBudget: z.number().min(0),
  footballBudget: z.number().min(0),
  coachingBudget: z.number().min(0),
  recruitingBudget: z.number().min(0),
  medicalBudget: z.number().min(0),
  facilitiesBudget: z.number().min(0),
  academicBudget: z.number().min(0),
  nilCapacity: z.number().min(0),
  donorSupport: z.number().min(0).max(100),
  mediaRevenue: z.number().min(0),
  currentBalance: z.number(),
  recruitingCommitted: z.number().min(0),
  medicalCommitted: z.number().min(0),
  nilCommitted: z.number().min(0),
  facilitiesLevel: z.number().min(0).max(100),
  medicalLevel: z.number().min(0).max(100),
  academicSupportLevel: z.number().min(0).max(100),
  donorConfidence: z.number().min(0).max(100),
  boardPatience: z.number().min(0).max(100),
  financialPressure: z.number().min(0).max(100),
  spendingPriority: z.enum(["balanced", "recruiting", "development", "medical", "facilities"]),
  lastBudgetYear: z.number().int().min(2020).max(2200),
});

const ecosystemPlayerEligibilitySchema = z.object({
  model: z.enum(["high-school", "legacy-four-in-five", "age-based-five-year"]),
  initialEnrollmentYear: z.number().int().min(2020).max(2200),
  windowStartYear: z.number().int().min(2020).max(2200),
  windowEndYear: z.number().int().min(2020).max(2200),
  athleticallyEligible: z.boolean(),
  academicStanding: z.enum(["good", "warning", "ineligible"]),
  termCredits: z.number().min(0).max(30),
  degreeProgress: z.number().min(0).max(100),
  gamesPlayedThisSeason: z.number().int().min(0).max(30),
  redshirtUsed: z.boolean(),
  scholarshipStatus: z.enum(["none", "partial", "full"]),
});

const ecosystemTalentProfileSchema = z.object({
  regionId: z.string().min(1),
  homeState: z.string().length(2),
  graduationYear: z.number().int().min(2020).max(2200),
  route: z.enum(["traditional", "multi-sport", "late-bloomer", "juco", "walk-on"]),
  developmentCurve: z.enum(["early", "steady", "late"]),
  physicalMaturity: z.number().min(0).max(100),
  scoutingGrade: z.number().min(0).max(100),
  campExposure: z.number().min(0).max(100),
  exposure: z.enum(["hidden", "local", "regional", "national"]),
  academicProjection: z.number().min(0).max(100),
  discoveredYear: z.number().int().min(2020).max(2200),
});

const ecosystemTalentPipelineSchema = z.object({
  version: z.literal(1),
  generationYear: z.number().int().min(2020).max(2200),
  regions: z.array(z.object({
    id: z.string().min(1), name: z.string().min(2), stateCodes: z.array(z.string().length(2)).min(1),
    populationWeight: z.number().min(0).max(100), footballCulture: z.number().min(0).max(100),
    infrastructure: z.number().min(0).max(100), exposureBias: z.number().min(0).max(100),
    academicAccess: z.number().min(0).max(100), annualClassSize: z.number().int().positive(),
  })).min(4),
  camps: z.array(z.object({
    id: z.string().min(1), name: z.string().min(2), regionId: z.string().min(1),
    phase: z.enum(["summer-recruiting", "spring-development"]),
    phaseWeek: z.number().int().min(1).max(30), prestige: z.number().min(0).max(100),
    capacity: z.number().int().positive(), lastHeldSeasonYear: z.number().int().min(2019).max(2200),
  })),
  independentProspects: z.array(z.object({
    id: z.string().min(1), seed: z.string().min(1), name: z.string().min(2),
    age: z.number().int().min(17).max(23), position: ecosystemRosterPositionSchema,
    route: z.enum(["juco", "walk-on"]), regionId: z.string().min(1), homeState: z.string().length(2),
    overall: z.number().min(0).max(100), potential: z.number().min(0).max(100), health: z.number().min(0).max(100),
    academicProjection: z.number().min(0).max(100), exposure: z.enum(["hidden", "local", "regional", "national"]),
    campExposure: z.number().min(0).max(100), graduationYear: z.number().int().min(2020).max(2200),
    yearsInRoute: z.number().int().min(0).max(4), status: z.enum(["available", "contacted", "committed"]),
    committedTeamId: z.string().min(1).optional(),
  })),
  classHistory: z.array(z.object({
    seasonYear: z.number().int().min(2020).max(2200), generatedPlayers: z.number().int().nonnegative(),
    traditionalPlayers: z.number().int().nonnegative(), multiSportPlayers: z.number().int().nonnegative(),
    lateBloomers: z.number().int().nonnegative(), jucoEntries: z.number().int().nonnegative(),
    walkOnEntries: z.number().int().nonnegative(), topProspectIds: z.array(z.string().min(1)),
  })),
});

const ecosystemPositionProjectionSchema = z.object({
  position: ecosystemRosterPositionSchema,
  currentPlayers: z.number().int().nonnegative(),
  returningNextYear: z.number().int().nonnegative(),
  returningInTwoYears: z.number().int().nonnegative(),
  projectedDepartures: z.number().int().nonnegative(),
  scholarshipPlayers: z.number().int().nonnegative(),
  averageOverall: z.number().min(0).max(100),
  bestOverall: z.number().min(0).max(100),
  averagePotential: z.number().min(0).max(100),
  needNow: z.number().min(0).max(100),
  needNextYear: z.number().min(0).max(100),
  targetAdds: z.number().int().min(0).max(6),
});

const ecosystemRosterPlanSchema = z.object({
  version: z.literal(1),
  seasonYear: z.number().int().min(2020).max(2200),
  reviewedWeek: z.number().int().nonnegative(),
  strategy: z.enum(["contend", "balanced", "develop", "rebuild"]),
  planningHorizonYears: z.literal(3),
  targetClassSize: z.number().int().nonnegative().max(28),
  availableRosterSpots: z.number().int().nonnegative(),
  availableScholarships: z.number().int().nonnegative(),
  projectedDepartures: z.number().int().nonnegative(),
  retentionRisk: z.number().min(0).max(100),
  redshirtPlayerIds: z.array(z.string().min(1)),
  developmentalPlayerIds: z.array(z.string().min(1)),
  positionChanges: z.array(z.object({
    playerId: z.string().min(1),
    fromPosition: ecosystemRosterPositionSchema,
    toPosition: ecosystemRosterPositionSchema,
    reason: z.string().min(2),
    applied: z.boolean(),
  })),
  scholarshipDecisions: z.array(z.object({
    playerId: z.string().min(1),
    previousStatus: z.enum(["none", "partial", "full"]),
    nextStatus: z.enum(["partial", "full"]),
    reason: z.string().min(2),
  })),
  positionProjections: z.object({
    QB: ecosystemPositionProjectionSchema,
    RB: ecosystemPositionProjectionSchema,
    WR: ecosystemPositionProjectionSchema,
    TE: ecosystemPositionProjectionSchema,
    OT: ecosystemPositionProjectionSchema,
    OG: ecosystemPositionProjectionSchema,
    C: ecosystemPositionProjectionSchema,
    EDGE: ecosystemPositionProjectionSchema,
    DT: ecosystemPositionProjectionSchema,
    LB: ecosystemPositionProjectionSchema,
    CB: ecosystemPositionProjectionSchema,
    S: ecosystemPositionProjectionSchema,
    K: ecosystemPositionProjectionSchema,
    P: ecosystemPositionProjectionSchema,
  }),
  lastReviewReason: z.string().min(2),
});


const ecosystemMovementMarketSchema = z.object({
  version: z.literal(1),
  seasonYear: z.number().int().min(2020).max(2200),
  lastProcessedDay: z.number().int().nonnegative(),
  openings: z.array(z.object({
    id: z.string().min(1),
    teamId: z.string().min(1),
    position: ecosystemRosterPositionSchema,
    seasonYear: z.number().int().min(2020).max(2200),
    slots: z.number().int().nonnegative(),
    scholarshipSlots: z.number().int().nonnegative(),
    nilAvailable: z.number().min(0),
    recruitingAvailable: z.number().min(0),
    filledByCandidateIds: z.array(z.string().min(1)),
    status: z.enum(["open", "filled", "closed"]),
    reason: z.string().min(2),
  })),
  negotiations: z.array(z.object({
    id: z.string().min(1),
    candidateId: z.string().min(1),
    candidateKind: z.enum(["high-school", "juco", "walk-on", "transfer"]),
    candidateName: z.string().min(2),
    position: ecosystemRosterPositionSchema,
    teamId: z.string().min(1),
    status: z.enum(["offered", "accepted", "withdrawn", "expired"]),
    scholarship: z.enum(["none", "partial", "full"]),
    nilOffer: z.number().min(0),
    promisedRole: z.enum(["starter-path", "rotation", "developmental"]),
    score: z.number().min(0).max(100),
    createdWeek: z.number().int().min(1),
    expiresWeek: z.number().int().min(1),
    reason: z.string().min(2),
  })),
  coachVacancies: z.array(z.object({
    id: z.string().min(1),
    teamId: z.string().min(1),
    role: z.enum(["head-coach", "offensive-coordinator", "defensive-coordinator", "position-coach"]),
    status: z.enum(["open", "filled", "cancelled"]),
    openedSeasonYear: z.number().int().min(2020).max(2200),
    openedWeek: z.number().int().min(1),
    salaryBudget: z.number().min(0),
    reason: z.string().min(2),
    formerCoachId: z.string().min(1).optional(),
    hiredCoachId: z.string().min(1).optional(),
  })),
  acceptedMoves: z.number().int().nonnegative(),
  withdrawnOffers: z.number().int().nonnegative(),
  digest: z.array(z.string().min(2)).max(6),
});


const ecosystemCompetitionGameSchema = z.object({
  id: z.string().min(1),
  seasonYear: z.number().int().min(2020).max(2200),
  week: z.number().int().min(1).max(20),
  kind: z.enum(["conference", "nonconference", "rivalry", "conference-championship", "playoff", "bowl"]),
  homeTeamId: z.string().min(1),
  awayTeamId: z.string().min(1),
  neutralSite: z.boolean(),
  conferenceGame: z.boolean(),
  rivalryId: z.string().min(1).optional(),
  status: z.enum(["scheduled", "complete"]),
  homeScore: z.number().int().nonnegative().optional(),
  awayScore: z.number().int().nonnegative().optional(),
  winnerTeamId: z.string().min(1).optional(),
  loserTeamId: z.string().min(1).optional(),
  upset: z.boolean().optional(),
});

const ecosystemNationalRankingSchema = z.object({
  seasonYear: z.number().int().min(2020).max(2200),
  week: z.number().int().nonnegative().max(20),
  teamId: z.string().min(1),
  rank: z.number().int().min(1),
  previousRank: z.number().int().min(1).optional(),
  score: z.number().min(0).max(100),
  strengthOfSchedule: z.number().min(0).max(100),
  qualityWins: z.number().int().nonnegative(),
  pointDifferential: z.number().int(),
});

const ecosystemCompetitionSchema = z.object({
  version: z.literal(1),
  seasonYear: z.number().int().min(2020).max(2200),
  schedule: z.array(ecosystemCompetitionGameSchema),
  rankings: z.array(ecosystemNationalRankingSchema),
  rankingHistory: z.array(z.object({
    seasonYear: z.number().int().min(2020).max(2200),
    week: z.number().int().nonnegative().max(20),
    rankings: z.array(ecosystemNationalRankingSchema),
  })),
  playoff: z.object({
    seasonYear: z.number().int().min(2020).max(2200),
    stage: z.enum(["regular-season", "conference-championships", "quarterfinals", "semifinals", "national-championship", "complete"]),
    seedTeamIds: z.array(z.string().min(1)),
    gameIds: z.array(z.string().min(1)),
    championTeamId: z.string().min(1).optional(),
  }),
  awards: z.array(z.object({
    id: z.string().min(1),
    seasonYear: z.number().int().min(2020).max(2200),
    week: z.number().int().min(1).max(20).optional(),
    kind: z.enum(["player-of-week", "conference-player", "national-player", "position-award", "all-american"]),
    playerId: z.string().min(1),
    teamId: z.string().min(1),
    title: z.string().min(2),
    detail: z.string().min(2),
  })),
  rivalries: z.array(z.object({
    id: z.string().min(1),
    name: z.string().min(2),
    teamAId: z.string().min(1),
    teamBId: z.string().min(1),
    intensity: z.number().min(0).max(100),
    meetings: z.number().int().nonnegative(),
    winsA: z.number().int().nonnegative(),
    winsB: z.number().int().nonnegative(),
    ties: z.number().int().nonnegative(),
    streak: z.number().int().nonnegative(),
    lastWinnerTeamId: z.string().min(1).optional(),
  })),
  programLegacies: z.array(z.object({
    teamId: z.string().min(1),
    allTimeWins: z.number().int().nonnegative(),
    allTimeLosses: z.number().int().nonnegative(),
    nationalTitles: z.number().int().nonnegative(),
    playoffAppearances: z.number().int().nonnegative(),
    bowlWins: z.number().int().nonnegative(),
    rivalryWins: z.number().int().nonnegative(),
    bestRank: z.number().int().min(1),
    reputation: z.number().min(0).max(100),
    eraLabel: z.enum(["unknown", "building", "contender", "power", "dynasty", "decline"]),
  })),
  digest: z.array(z.string().min(2)).max(6),
});

const ecosystemPositionRoleSchema = z.enum([
  "pocket-distributor", "dual-threat", "field-general",
  "zone-runner", "power-back", "receiving-back",
  "separator", "vertical-threat", "possession-target",
  "inline-receiver", "seam-threat", "move-tight-end",
  "blindside-anchor", "zone-tackle", "power-tackle",
  "pull-guard", "phone-booth-guard", "zone-guard",
  "line-caller", "reach-center", "power-center",
  "speed-rusher", "power-rusher", "edge-setter",
  "nose-anchor", "interior-penetrator", "three-technique",
  "run-anchor", "coverage-backer", "edge-blitzer",
  "press-corner", "zone-corner", "ball-hawk",
  "box-safety", "center-fielder", "match-safety",
  "accuracy-kicker", "power-kicker", "clutch-kicker",
  "directional-punter", "hangtime-punter", "field-position-punter",
]);

const ecosystemTacticalIdentitySchema = z.object({
  version: z.literal(1),
  offenseSystem: z.enum(["air-raid", "west-coast", "power-run", "spread-option", "multiple"]),
  defenseSystem: z.enum(["quarters-425", "multiple-34", "over-43", "nickel-match", "man-pressure", "multiple-defense"]),
  tempo: z.enum(["controlled", "balanced", "fast"]),
  offensiveAggression: z.enum(["conservative", "balanced", "aggressive"]),
  defensiveAggression: z.enum(["conservative", "balanced", "aggressive"]),
  complexity: z.number().min(0).max(100),
  installation: z.number().min(0).max(100),
  continuity: z.number().min(0).max(100),
  rotationDepth: z.number().min(0).max(100),
  headCoachFingerprint: z.string().min(1),
  offensiveCoordinatorFingerprint: z.string().min(1).default("legacy-offense"),
  defensiveCoordinatorFingerprint: z.string().min(1).default("legacy-defense"),
  staffFingerprint: z.string().min(1).default("legacy-staff"),
  runRate: z.number().min(0).max(100).default(48),
  playActionRate: z.number().min(0).max(100).default(18),
  screenRate: z.number().min(0).max(100).default(12),
  deepShotRate: z.number().min(0).max(100).default(20),
  blitzRate: z.number().min(0).max(100).default(34),
  manCoverageRate: z.number().min(0).max(100).default(42),
  disguiseRate: z.number().min(0).max(100).default(58),
  fourthDownAggression: z.number().min(0).max(100).default(52),
  adaptation: z.number().min(0).max(100).default(58),
  positionRoles: z.object({
    QB: z.object({ primary: ecosystemPositionRoleSchema, secondary: ecosystemPositionRoleSchema }),
    RB: z.object({ primary: ecosystemPositionRoleSchema, secondary: ecosystemPositionRoleSchema }),
    WR: z.object({ primary: ecosystemPositionRoleSchema, secondary: ecosystemPositionRoleSchema }),
    TE: z.object({ primary: ecosystemPositionRoleSchema, secondary: ecosystemPositionRoleSchema }),
    OT: z.object({ primary: ecosystemPositionRoleSchema, secondary: ecosystemPositionRoleSchema }),
    OG: z.object({ primary: ecosystemPositionRoleSchema, secondary: ecosystemPositionRoleSchema }),
    C: z.object({ primary: ecosystemPositionRoleSchema, secondary: ecosystemPositionRoleSchema }),
    EDGE: z.object({ primary: ecosystemPositionRoleSchema, secondary: ecosystemPositionRoleSchema }),
    DT: z.object({ primary: ecosystemPositionRoleSchema, secondary: ecosystemPositionRoleSchema }),
    LB: z.object({ primary: ecosystemPositionRoleSchema, secondary: ecosystemPositionRoleSchema }),
    CB: z.object({ primary: ecosystemPositionRoleSchema, secondary: ecosystemPositionRoleSchema }),
    S: z.object({ primary: ecosystemPositionRoleSchema, secondary: ecosystemPositionRoleSchema }),
    K: z.object({ primary: ecosystemPositionRoleSchema, secondary: ecosystemPositionRoleSchema }),
    P: z.object({ primary: ecosystemPositionRoleSchema, secondary: ecosystemPositionRoleSchema }),
  }),
});

const ecosystemPlayerTacticalProfileSchema = z.object({
  version: z.literal(1),
  archetype: ecosystemPositionRoleSchema,
  preferredRole: ecosystemPositionRoleSchema,
  secondaryRole: ecosystemPositionRoleSchema,
  schemeFit: z.number().min(0).max(100),
  roleFit: z.number().min(0).max(100),
  learning: z.number().min(0).max(100),
  versatility: z.number().min(0).max(100),
  lastEvaluatedSeason: z.number().int().min(0).max(2200),
  lastCoachFingerprint: z.string().min(1).optional(),
});


const ecosystemSocialSchema = z.object({
  version: z.literal(1),
  seasonYear: z.number().int().min(2020).max(2200),
  lastProcessedDay: z.number().int().nonnegative(),
  bonds: z.array(z.object({
    id: z.string().min(1),
    entityAId: z.string().min(1),
    entityBId: z.string().min(1),
    entityAKind: z.enum(["player", "coach"]),
    entityBKind: z.enum(["player", "coach"]),
    teamId: z.string().min(1).optional(),
    kind: z.enum(["teammate", "position-rival", "mentor", "coach-player", "staff"]),
    trust: z.number().min(0).max(100),
    respect: z.number().min(0).max(100),
    chemistry: z.number().min(0).max(100),
    tension: z.number().min(0).max(100),
    influence: z.number().min(0).max(100),
    familiarityWeeks: z.number().int().nonnegative().max(999),
    active: z.boolean(),
    lastSeasonYear: z.number().int().min(2020).max(2200),
    lastWeek: z.number().int().min(1).max(60),
  })).max(12000),
  teamCultures: z.array(z.object({
    teamId: z.string().min(1),
    cohesion: z.number().min(0).max(100),
    accountability: z.number().min(0).max(100),
    coachTrust: z.number().min(0).max(100),
    leadership: z.number().min(0).max(100),
    conflict: z.number().min(0).max(100),
    morale: z.number().min(0).max(100),
    stability: z.number().min(0).max(100),
    lastSeasonYear: z.number().int().min(2020).max(2200),
    lastWeek: z.number().int().min(1).max(60),
  })),
  incidents: z.array(z.object({
    id: z.string().min(1),
    kind: z.enum(["mentorship", "locker-room-conflict", "leadership", "reconciliation", "staff-friction", "broken-promise"]),
    seasonYear: z.number().int().min(2020).max(2200),
    week: z.number().int().min(1).max(60),
    teamId: z.string().min(1),
    participantIds: z.array(z.string().min(1)).min(1),
    title: z.string().min(2),
    detail: z.string().min(2),
    impact: z.number().min(-10).max(10),
  })).max(180),
  digest: z.array(z.string().min(2)).max(6),
});

const ecosystemCareerEventSchema = z.object({
  id: z.string().min(1),
  seasonYear: z.number().int().min(2020).max(2200),
  week: z.number().int().min(0).max(400),
  kind: z.enum(["created", "enrolled", "transferred", "position-change", "graduated", "declared", "drafted", "signed", "released", "retired"]),
  detail: z.string().min(2),
  fromTeamId: z.string().min(1).optional(),
  toTeamId: z.string().min(1).optional(),
});

const ecosystemCareerRegistrySchema = z.object({
  version: z.literal(1),
  records: z.array(z.object({
    playerId: z.string().min(1),
    name: z.string().min(2),
    position: ecosystemRosterPositionSchema,
    age: z.number().int().min(14).max(45),
    overall: z.number().min(0).max(100),
    potential: z.number().min(0).max(100),
    currentStage: z.enum(["high-school", "college", "draft-pool", "professional", "free-agent", "retired", "football-exit"]),
    currentTeamId: z.string().min(1).optional(),
    highSchoolTeamIds: z.array(z.string().min(1)),
    collegeTeamIds: z.array(z.string().min(1)),
    professionalTeamIds: z.array(z.string().min(1)),
    isHero: z.boolean(),
    draftYear: z.number().int().min(2020).max(2200).optional(),
    draftRound: z.number().int().min(1).max(7).optional(),
    draftPick: z.number().int().min(1).optional(),
    retiredYear: z.number().int().min(2020).max(2200).optional(),
    events: z.array(ecosystemCareerEventSchema).max(48),
  })).max(20000),
  draftPoolIds: z.array(z.string().min(1)),
  retiredIds: z.array(z.string().min(1)),
  lastSyncedSeasonYear: z.number().int().min(2020).max(2200),
}).default({ version: 1, records: [], draftPoolIds: [], retiredIds: [], lastSyncedSeasonYear: 2020 });

const ecosystemHistoryFactSchema = z.object({
  id: z.string().min(1),
  sourceType: z.enum(["story", "transaction"]),
  sourceId: z.string().min(1),
  seasonYear: z.number().int().min(2020).max(2200),
  week: z.number().int().min(1).max(400),
  createdOn: gameDateSchema,
  kind: z.enum(["breakout", "injury", "depth-change", "commitment", "coach-pressure", "coach-move", "upset", "market-shift", "conference-race", "championship", "transfer", "graduation", "enrollment", "investment", "budget-crunch", "nil-battle", "resource-shift", "talent-class", "camp-breakout", "juco-route", "walk-on-route", "roster-plan", "position-change", "redshirt", "scholarship", "offer", "offer-withdrawn", "market-chain", "coach-vacancy", "tactical-change", "scheme-fit", "ranking", "playoff", "award", "rivalry", "bowl", "mentorship", "locker-room-conflict", "leadership", "reconciliation", "staff-friction", "broken-promise", "storyline", "portal-entry", "coach-fired", "coach-hired", "recruit-enrolled", "facility-investment", "budget-cut", "nil-commitment", "juco-entry", "walk-on-entry", "talent-enrolled", "scholarship-awarded", "redshirt-assigned", "offer-issued"]),
  title: z.string().min(2),
  detail: z.string().min(2),
  importance: z.union([z.literal(1), z.literal(2), z.literal(3), z.literal(4), z.literal(5)]),
  teamIds: z.array(z.string().min(1)),
  playerIds: z.array(z.string().min(1)),
  coachIds: z.array(z.string().min(1)),
  relatedToHero: z.boolean(),
});

const ecosystemObjectiveSchema = z.object({
  id: z.string().min(1),
  ownerKind: z.enum(["team", "player", "coach"]),
  ownerId: z.string().min(1),
  kind: z.enum(["win-target", "rebuild-program", "protect-job", "build-program", "earn-starting-role", "breakout-season"]),
  status: z.enum(["active", "achieved", "failed"]),
  createdSeasonYear: z.number().int().min(2020).max(2200),
  createdWeek: z.number().int().min(1).max(400),
  targetSeasonYear: z.number().int().min(2020).max(2200),
  progress: z.number().min(0).max(1000),
  target: z.number().min(0).max(1000),
  title: z.string().min(2),
  detail: z.string().min(2),
  evidenceFactIds: z.array(z.string().min(1)).max(16),
  completedSeasonYear: z.number().int().min(2020).max(2200).optional(),
  completedWeek: z.number().int().min(1).max(400).optional(),
});

const ecosystemStoryArcSchema = z.object({
  id: z.string().min(1),
  kind: z.enum(["player-rise", "career-crossroads", "coach-tenure", "team-run", "rivalry-era", "program-rebuild"]),
  status: z.enum(["emerging", "active", "resolved"]),
  title: z.string().min(2),
  summary: z.string(),
  teamIds: z.array(z.string().min(1)),
  playerIds: z.array(z.string().min(1)),
  coachIds: z.array(z.string().min(1)),
  startedSeasonYear: z.number().int().min(2020).max(2200),
  startedWeek: z.number().int().min(1).max(400),
  lastSeasonYear: z.number().int().min(2020).max(2200),
  lastWeek: z.number().int().min(1).max(400),
  momentum: z.number().min(-100).max(100),
  chapters: z.number().int().nonnegative().max(1000),
  factIds: z.array(z.string().min(1)).max(16),
  relatedToHero: z.boolean(),
});

const ecosystemWorldHistorySchema = z.object({
  version: z.literal(1),
  lastProcessedSeasonYear: z.number().int().min(2020).max(2200),
  lastProcessedWeek: z.number().int().min(1).max(400),
  processedSourceIds: z.array(z.string().min(1)).max(1800),
  facts: z.array(ecosystemHistoryFactSchema).max(1200),
  objectives: z.array(ecosystemObjectiveSchema).max(420),
  arcs: z.array(ecosystemStoryArcSchema).max(180),
  digest: z.array(z.string().min(2)).max(6),
});

const footballEcosystemSchema = z.object({
  moduleVersion: z.literal(13),
  constitution: worldConstitutionSchema,
  cycle: worldCycleSchema,
  lastSimulatedDay: z.number().int().nonnegative(),
  currentWeek: z.number().int().min(1),
  lastUpdatedOn: gameDateSchema,
  seasonYear: z.number().int().min(2020).max(2200),
  seasonWeek: z.number().int().min(1).max(20),
  phase: z.enum(["regular-season", "postseason", "offseason"]),
  lastOffseasonYear: z.number().int().min(2019).max(2200),
  conferences: z.array(z.object({
    id: z.string().min(1),
    name: z.string().min(2),
    shortName: z.string().min(1),
    region: z.string().min(2),
    prestige: z.number().min(0).max(100),
    teamIds: z.array(z.string().min(1)).min(2),
    champions: z.array(z.object({ seasonYear: z.number().int(), teamId: z.string().min(1) })),
  })).min(2),
  teams: z.array(z.object({
    id: z.string().min(1),
    seed: z.string().min(1),
    name: z.string().min(2),
    shortName: z.string().min(1),
    level: z.enum(["high-school", "college"]),
    stateCode: z.string().length(2),
    conferenceId: z.string().min(1).optional(),
    prestige: z.number().min(0).max(100),
    rating: z.number().min(0).max(100),
    expectation: z.number().min(0).max(100),
    wins: z.number().int().nonnegative(),
    losses: z.number().int().nonnegative(),
    conferenceWins: z.number().int().nonnegative(),
    conferenceLosses: z.number().int().nonnegative(),
    streak: z.number().int(),
    championships: z.number().int().nonnegative(),
    offenseStyle: z.string().min(2),
    defenseStyle: z.string().min(2),
    positionNeeds: ecosystemPositionNeedsSchema,
    rosterIds: z.array(z.string().min(1)),
    coachIds: z.array(z.string().min(1)),
    trend: z.enum(["rising", "stable", "falling"]),
    compliance: ecosystemTeamComplianceSchema,
    resources: ecosystemProgramResourcesSchema,
    rosterPlan: ecosystemRosterPlanSchema,
    tactical: ecosystemTacticalIdentitySchema,
  })).min(10),
  players: z.array(z.object({
    id: z.string().min(1),
    seed: z.string().min(1),
    name: z.string().min(2),
    teamId: z.string().min(1),
    level: z.enum(["high-school", "college"]),
    age: z.number().int().min(14).max(24),
    classYear: z.enum(["Freshman", "Sophomore", "Junior", "Senior"]),
    position: ecosystemRosterPositionSchema,
    overall: z.number().min(0).max(100),
    potential: z.number().min(0).max(100),
    health: z.number().min(0).max(100),
    form: z.number().min(0).max(100),
    status: z.enum(["starter", "rotation", "backup", "injured"]),
    depthRank: z.number().int().min(1),
    trajectory: z.enum(["surging", "steady", "slipping"]),
    nationalRank: z.number().int().min(1),
    recruitingStage: z.enum(["unranked", "tracked", "offered", "committed"]),
    committedTeamId: z.string().min(1).optional(),
    eligibilityYears: z.number().int().min(0).max(6),
    seasonsPlayed: z.number().int().nonnegative(),
    transferStatus: z.enum(["none", "portal", "transferred"]),
    previousTeamIds: z.array(z.string().min(1)),
    isHero: z.boolean(),
    eligibility: ecosystemPlayerEligibilitySchema,
    talent: ecosystemTalentProfileSchema,
    usagePlan: z.enum(["starter", "rotation", "special-teams", "developmental", "redshirt"]),
    positionHistory: z.array(ecosystemRosterPositionSchema),
    tactical: ecosystemPlayerTacticalProfileSchema,
  })).min(40),
  coaches: z.array(z.object({
    id: z.string().min(1),
    seed: z.string().min(1),
    name: z.string().min(2),
    teamId: z.string().min(1),
    role: z.enum(["head-coach", "offensive-coordinator", "defensive-coordinator", "position-coach"]),
    age: z.number().int().min(25).max(80),
    reputation: z.number().min(0).max(100),
    development: z.number().min(0).max(100),
    recruiting: z.number().min(0).max(100),
    pressure: z.number().min(0).max(100),
    jobSecurity: z.number().min(0).max(100),
    status: z.enum(["secure", "watched", "hot-seat"]),
    philosophy: z.string().min(2),
    tactics: z.number().min(0).max(100).default(60),
    adaptability: z.number().min(0).max(100).default(58),
    gameManagement: z.number().min(0).max(100).default(58),
    temperament: z.enum(["calm", "demanding", "volatile", "player-first"]).default("calm"),
    offenseSystem: z.enum(["air-raid", "west-coast", "power-run", "spread-option", "multiple"]).default("multiple"),
    defenseSystem: z.enum(["quarters-425", "multiple-34", "over-43", "nickel-match", "man-pressure", "multiple-defense"]).default("multiple-defense"),
    specialtyPositions: z.array(ecosystemRosterPositionSchema).default([]),
    contractYears: z.number().int().min(0).max(10).default(2),
    annualSalary: z.number().int().nonnegative().default(500000),
    tenureYears: z.number().int().nonnegative(),
    careerWins: z.number().int().nonnegative(),
    careerLosses: z.number().int().nonnegative(),
    previousTeamIds: z.array(z.string().min(1)),
  })).min(10),
  stories: z.array(z.object({
    id: z.string().min(1),
    kind: z.enum(["breakout", "injury", "depth-change", "commitment", "coach-pressure", "coach-move", "upset", "market-shift", "conference-race", "championship", "transfer", "graduation", "enrollment", "investment", "budget-crunch", "nil-battle", "resource-shift", "talent-class", "camp-breakout", "juco-route", "walk-on-route", "roster-plan", "position-change", "redshirt", "scholarship", "offer", "offer-withdrawn", "market-chain", "coach-vacancy", "tactical-change", "scheme-fit", "ranking", "playoff", "award", "rivalry", "bowl", "mentorship", "locker-room-conflict", "leadership", "reconciliation", "staff-friction", "broken-promise", "storyline"]),
    createdOn: gameDateSchema,
    week: z.number().int().min(1),
    title: z.string().min(2),
    detail: z.string().min(2),
    importance: z.union([z.literal(1), z.literal(2), z.literal(3), z.literal(4), z.literal(5)]),
    teamIds: z.array(z.string().min(1)),
    playerIds: z.array(z.string().min(1)),
    coachIds: z.array(z.string().min(1)),
    relatedToHero: z.boolean(),
  })),
  digest: z.array(z.string().min(2)).max(6),
  market: z.object({
    openScholarships: z.number().int().nonnegative(),
    activeRecruitments: z.number().int().nonnegative(),
    committedPlayers: z.number().int().nonnegative(),
    coachingHotSeats: z.number().int().nonnegative(),
    portalPlayers: z.number().int().nonnegative(),
    coachOpenings: z.number().int().nonnegative(),
    totalRecruitingBudget: z.number().min(0),
    totalNilCapacity: z.number().min(0),
    programsUnderFinancialPressure: z.number().int().nonnegative(),
    annualProspects: z.number().int().nonnegative(),
    jucoProspects: z.number().int().nonnegative(),
    walkOnProspects: z.number().int().nonnegative(),
    nationallyExposedProspects: z.number().int().nonnegative(),
    plannedClassSpots: z.number().int().nonnegative(),
    developmentalPlayers: z.number().int().nonnegative(),
    plannedPositionChanges: z.number().int().nonnegative(),
    activeNegotiations: z.number().int().nonnegative(),
    withdrawnOffers: z.number().int().nonnegative(),
    transferCandidates: z.number().int().nonnegative(),
    lowSchemeFitPlayers: z.number().int().nonnegative(),
    programsInstallingNewSystems: z.number().int().nonnegative(),
  }),
  teamHistory: z.array(z.object({
    id: z.string().min(1),
    seasonYear: z.number().int(),
    teamId: z.string().min(1),
    conferenceId: z.string().min(1),
    wins: z.number().int().nonnegative(),
    losses: z.number().int().nonnegative(),
    conferenceWins: z.number().int().nonnegative(),
    conferenceLosses: z.number().int().nonnegative(),
    finalRating: z.number().min(0).max(100),
    finish: z.number().int().min(1),
    conferenceChampion: z.boolean(),
    headCoachId: z.string().min(1).optional(),
  })),
  transactions: z.array(z.object({
    id: z.string().min(1),
    kind: z.enum(["portal-entry", "transfer", "coach-fired", "coach-hired", "graduation", "recruit-enrolled", "facility-investment", "budget-cut", "nil-commitment", "juco-entry", "walk-on-entry", "talent-enrolled", "position-change", "scholarship-awarded", "redshirt-assigned", "offer-issued", "offer-withdrawn", "commitment", "coach-vacancy", "tactical-change", "scheme-fit"]),
    seasonYear: z.number().int(),
    week: z.number().int().min(1),
    createdOn: gameDateSchema,
    title: z.string().min(2),
    detail: z.string().min(2),
    playerId: z.string().min(1).optional(),
    coachId: z.string().min(1).optional(),
    fromTeamId: z.string().min(1).optional(),
    toTeamId: z.string().min(1).optional(),
    relatedToHero: z.boolean(),
  })),
  talentPipeline: ecosystemTalentPipelineSchema,
  movementMarket: ecosystemMovementMarketSchema,
  competition: ecosystemCompetitionSchema,
  social: ecosystemSocialSchema,
  careerRegistry: ecosystemCareerRegistrySchema,
  worldHistory: ecosystemWorldHistorySchema,
});

const careerMetaSchema = z.object({
  id: z.string().min(1),
  schemaVersion: z.literal(CURRENT_SCHEMA_VERSION),
  sport: z.literal("american-football"),
  worldSeed: z.string().min(1),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
  currentDate: gameDateSchema,
  phase: z.enum(["high-school-preseason", "college-orientation", "college-season", "professional-draft", "professional-career"]),
  revision: z.number().int().nonnegative(),
});

const historyEntrySchema = z.object({
  id: z.string().min(1),
  occurredAt: z.string().datetime(),
  type: z.string().min(1),
  title: z.string().min(1),
  description: z.string().min(1),
});

export const careerSaveSchema = z.object({
  meta: careerMetaSchema,
  character: characterSchema,
  life: lifeSchema,
  football: footballSchema,
  relationships: relationshipsSchema,
  world: footballEcosystemSchema,
  history: z.array(historyEntrySchema),
});

export type CareerSave = z.infer<typeof careerSaveSchema>;

export interface CareerIndexRecord {
  id: string;
  displayName: string;
  sport: "american-football";
  phase: "high-school-preseason" | "college-orientation" | "college-season" | "professional-draft" | "professional-career";
  currentDate: string;
  updatedAt: string;
  revision: number;
  position: "QB" | "RB" | "WR" | "TE" | "OT" | "OG" | "C" | "EDGE" | "DT" | "LB" | "CB" | "S" | "K" | "P";
  jerseyNumber: number;
  schoolName: string;
  seasonLabel: string;
  stateCode: string;
  overall: number;
  potentialBand: "role-player" | "starter" | "high-upside" | "national-ceiling";
}
