import { z } from "zod";

export const CURRENT_SCHEMA_VERSION = 22;

const gameDateSchema = z.object({
  year: z.number().int().min(1900).max(2200),
  month: z.number().int().min(1).max(12),
  day: z.number().int().min(1).max(31),
});

const personalitySchema = z.object({
  preset: z.enum(["obsessed", "composed", "electric", "underdog"]),
  discipline: z.number().min(0).max(100),
  ambition: z.number().min(0).max(100),
  confidence: z.number().min(0).max(100),
  composure: z.number().min(0).max(100),
  coachability: z.number().min(0).max(100),
  adaptability: z.number().min(0).max(100),
  riskTolerance: z.number().min(0).max(100),
  approvalNeed: z.number().min(0).max(100),
});

const characterSchema = z.object({
  identity: z.object({
    firstName: z.string().min(1),
    lastName: z.string().min(1),
    fullName: z.string().min(3),
    birthDate: z.string().min(10),
    age: z.number().int().min(15).max(22),
    gender: z.enum(["male", "female"]),
    handedness: z.enum(["right", "left"]),
  }),
  origin: z.object({
    country: z.literal("USA"),
    stateCode: z.string().length(2),
    stateName: z.string().min(2),
    city: z.string().min(2),
    region: z.string().min(2),
    familyIncome: z.enum(["strained", "working", "comfortable", "wealthy"]),
    familyStructure: z.enum(["two-parent", "single-parent", "extended-family"]),
    familySupport: z.enum(["demanding", "supportive", "hands-off"]),
    neighborhoodSafety: z.number().min(0).max(100),
    schoolQuality: z.number().min(0).max(100),
    trainingAccess: z.number().min(0).max(100),
    medicalAccess: z.number().min(0).max(100),
    footballCulture: z.number().min(0).max(100),
  }),
  personality: personalitySchema,
  physical: z.object({
    heightInches: z.number().int().min(60).max(84),
    weightLbs: z.number().int().min(130).max(360),
    frame: z.enum(["compact", "balanced", "long", "powerful"]),
    speed: z.number().min(0).max(100),
    strength: z.number().min(0).max(100),
    agility: z.number().min(0).max(100),
    stamina: z.number().min(0).max(100),
    explosiveness: z.number().min(0).max(100),
  }),
  education: z.object({
    gpa: z.number().min(0).max(4),
    academicAbility: z.number().min(0).max(100),
    attendance: z.number().min(0).max(100),
    eligibilityStatus: z.enum(["clear", "watch", "at-risk"]),
  }),
  condition: z.object({
    energy: z.number().min(0).max(100),
    fatigue: z.number().min(0).max(100),
    stress: z.number().min(0).max(100),
    confidence: z.number().min(0).max(100),
    health: z.number().min(0).max(100),
    sleepHours: z.number().min(0).max(24),
  }),
});

const schoolSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(2),
  shortName: z.string().min(2),
  mascot: z.string().min(2),
  city: z.string().min(2),
  stateCode: z.string().length(2),
  primaryColor: z.string().min(4),
  secondaryColor: z.string().min(4),
  prestige: z.number().min(0).max(100),
  facilities: z.number().min(0).max(100),
  coaching: z.number().min(0).max(100),
  medicine: z.number().min(0).max(100),
  discipline: z.number().min(0).max(100),
  youthTrust: z.number().min(0).max(100),
  philosophy: z.string().min(2),
});


const playerYearSchema = z.enum(["Freshman", "Sophomore", "Junior", "Senior"]);
const rosterPositionSchema = z.enum(["QB", "RB", "WR", "TE", "OL", "DL", "LB", "CB", "S", "K", "P"]);
const coachSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(3),
  role: z.enum(["head-coach", "position-coach", "offensive-coordinator", "defensive-coordinator"]),
  age: z.number().int().min(25).max(80),
  archetype: z.enum(["builder", "disciplinarian", "strategist", "recruiter"]),
  development: z.number().min(0).max(100),
  tactics: z.number().min(0).max(100),
  discipline: z.number().min(0).max(100),
  communication: z.number().min(0).max(100),
  youthPatience: z.number().min(0).max(100),
  pressure: z.number().min(0).max(100),
  relationship: z.number().min(0).max(100),
  summary: z.string().min(2),
});
const rosterPlayerSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(3),
  position: rosterPositionSchema,
  unit: z.enum(["offense", "defense", "special"]),
  year: playerYearSchema,
  overall: z.number().min(0).max(100),
  potential: z.number().min(0).max(100),
  style: z.string().min(2),
  coachStanding: z.number().min(0).max(100),
  health: z.number().min(0).max(100),
  status: z.enum(["starter", "rotation", "backup", "injured"]),
  depthRank: z.number().int().min(1),
});
const depthEvaluationSchema = z.object({
  heroScore: z.number(),
  comparisonScore: z.number(),
  gap: z.number().min(0),
  trend: z.enum(["rising", "stable", "falling"]),
  summary: z.string().min(2),
  reasons: z.array(z.string().min(2)).min(1),
  updatedOn: z.string().min(8),
});
const depthDecisionSchema = z.object({
  type: z.enum(["promoted", "demoted", "held"]),
  title: z.string().min(2),
  description: z.string().min(2),
  occurredOn: z.string().min(8),
});

const trainingFocusSchema = z.enum(["position-craft", "explosive-power", "film-install", "recovery-reset"]);
const trainingIntensitySchema = z.enum(["controlled", "standard", "aggressive"]);
const activeHealthIssueSchema = z.object({
  id: z.string().min(1),
  diagnosis: z.string().min(2),
  area: z.enum(["lower-body", "upper-body", "head-neck", "back-core"]),
  severity: z.enum(["minor", "moderate"]),
  daysRemaining: z.number().int().nonnegative(),
  recurrenceRisk: z.number().min(0).max(100),
  startedOn: z.string().min(8),
});
const trainingSessionSchema = z.object({
  id: z.string().min(1),
  date: gameDateSchema,
  focusId: trainingFocusSchema,
  focusName: z.string().min(2),
  intensity: trainingIntensitySchema,
  grade: z.enum(["A", "B", "C", "D"]),
  load: z.number().min(0).max(100),
  readinessBefore: z.number().min(0).max(100),
  readinessAfter: z.number().min(0).max(100),
  sorenessDelta: z.number(),
  riskAfter: z.number().min(0).max(100),
  gains: z.object({
    technique: z.number(),
    athleticism: z.number(),
    footballIq: z.number(),
    competitiveness: z.number(),
  }),
  note: z.string().min(2),
  issueOccurred: z.string().min(2).optional(),
});
const footballTrainingSchema = z.object({
  moduleVersion: z.literal(1),
  plan: z.object({
    focusId: trainingFocusSchema,
    intensity: trainingIntensitySchema,
    revision: z.number().int().min(1),
  }),
  body: z.object({
    readiness: z.number().min(0).max(100),
    acuteLoad: z.number().min(0).max(100),
    chronicLoad: z.number().min(0).max(100),
    soreness: z.number().min(0).max(100),
    pain: z.number().min(0).max(100),
    injuryRisk: z.number().min(0).max(100),
    medicalStatus: z.enum(["cleared", "questionable", "limited", "out"]),
    restriction: z.string().min(2),
    activeIssue: activeHealthIssueSchema.optional(),
  }),
  momentum: z.object({
    technique: z.number().min(0).max(100),
    athleticism: z.number().min(0).max(100),
    footballIq: z.number().min(0).max(100),
    competitiveness: z.number().min(0).max(100),
  }),
  lastSession: trainingSessionSchema.optional(),
});


const matchStatLineSchema = z.object({
  passingAttempts: z.number().int().nonnegative(),
  completions: z.number().int().nonnegative(),
  passingYards: z.number().int(),
  rushingAttempts: z.number().int().nonnegative(),
  rushingYards: z.number().int(),
  targets: z.number().int().nonnegative(),
  receptions: z.number().int().nonnegative(),
  receivingYards: z.number().int(),
  touchdowns: z.number().int().nonnegative(),
  turnovers: z.number().int().nonnegative(),
  tackles: z.number().int().nonnegative(),
  tacklesForLoss: z.number().int().nonnegative(),
  sacks: z.number().int().nonnegative(),
  passBreakups: z.number().int().nonnegative(),
  interceptions: z.number().int().nonnegative(),
});

const matchDecisionOptionSchema = z.object({
  id: z.string().min(1),
  label: z.string().min(2),
  detail: z.string().min(2),
  risk: z.enum(["safe", "balanced", "aggressive"]),
  focus: z.enum(["technique", "athleticism", "football-iq", "competitiveness"]),
  difficulty: z.number().min(0).max(100),
  upside: z.number().min(0).max(100),
  mistakeRisk: z.number().min(0).max(100),
});

const matchEpisodeSchema = z.object({
  id: z.string().min(1),
  unit: z.enum(["offense", "defense"]),
  position: z.enum(["QB", "RB", "WR", "LB", "CB"]),
  quarter: z.union([z.literal(1), z.literal(2), z.literal(3), z.literal(4)]),
  clockSeconds: z.number().int().min(0).max(900),
  down: z.union([z.literal(1), z.literal(2), z.literal(3), z.literal(4)]),
  distance: z.number().int().min(1).max(99),
  fieldPosition: z.number().int().min(0).max(100),
  scoreMargin: z.number().int(),
  title: z.string().min(2),
  situation: z.string().min(2),
  assignment: z.string().min(2),
  read: z.string().min(2),
  options: z.array(matchDecisionOptionSchema).min(3).max(4),
});

const matchEpisodeResultSchema = z.object({
  id: z.string().min(1),
  episodeId: z.string().min(1),
  optionId: z.string().min(1),
  grade: z.enum(["A", "B", "C", "D"]),
  headline: z.string().min(2),
  description: z.string().min(2),
  yards: z.number().int(),
  points: z.number().int().nonnegative(),
  coachDelta: z.number(),
  confidenceDelta: z.number(),
  fatigueDelta: z.number(),
  statDelta: matchStatLineSchema,
});

const footballMatchSchema = z.object({
  moduleVersion: z.literal(1),
  gameId: z.string().min(1),
  status: z.enum(["upcoming", "in-progress", "complete"]),
  scheduledWeek: z.number().int().min(1),
  scheduledDate: gameDateSchema,
  opponentId: z.string().min(1),
  opponentName: z.string().min(2),
  opponentRecord: z.string().min(1),
  opponentThreat: z.string().min(2),
  heroUnit: z.enum(["offense", "defense"]),
  heroScore: z.number().int().nonnegative(),
  opponentScore: z.number().int().nonnegative(),
  quarter: z.union([z.literal(1), z.literal(2), z.literal(3), z.literal(4)]),
  clockSeconds: z.number().int().min(0).max(900),
  heroFatigue: z.number().min(0).max(100),
  coachGrade: z.number().min(0).max(100),
  episodeIndex: z.number().int().nonnegative(),
  totalEpisodes: z.number().int().min(1),
  currentEpisode: matchEpisodeSchema.optional(),
  completedEpisodes: z.array(matchEpisodeResultSchema),
  stats: matchStatLineSchema,
  finalResult: z.object({
    won: z.boolean(),
    heroScore: z.number().int().nonnegative(),
    opponentScore: z.number().int().nonnegative(),
    grade: z.enum(["A", "B", "C", "D"]),
    headline: z.string().min(2),
    summary: z.string().min(2),
    spotlight: z.string().min(2),
    coachTrustDelta: z.number(),
    visibilityDelta: z.number(),
  }).optional(),
});

const recruitingProgramTierSchema = z.enum(["national", "power", "regional", "developmental"]);
const recruitingStageSchema = z.enum(["unaware", "watchlist", "evaluating", "contact", "priority", "offered", "cooled"]);
const projectedCollegeRoleSchema = z.enum(["immediate-competition", "rotation-path", "developmental", "long-shot"]);
const recruitingProgramSchema = z.object({
  id: z.string().min(1),
  seed: z.string().min(1),
  name: z.string().min(2),
  shortName: z.string().min(2),
  city: z.string().min(2),
  stateCode: z.string().length(2),
  distanceMiles: z.number().int().nonnegative(),
  tier: recruitingProgramTierSchema,
  prestige: z.number().min(0).max(100),
  conferenceLevel: z.number().min(0).max(100),
  scheme: z.string().min(2),
  academicStandard: z.number().min(0).max(100),
  medicine: z.number().min(0).max(100),
  facilities: z.number().min(0).max(100),
  youthOpportunity: z.number().min(0).max(100),
  positionNeed: z.number().min(0).max(100),
  depthCompetition: z.number().min(0).max(100),
  fit: z.number().min(0).max(100),
  interest: z.number().min(0).max(100),
  scoutingConfidence: z.number().min(0).max(100),
  stage: recruitingStageSchema,
  academicEligible: z.boolean(),
  medicalConcern: z.boolean(),
  projectedRole: projectedCollegeRoleSchema,
  recruiterName: z.string().min(2),
  recruiterStyle: z.enum(["direct", "patient", "salesman", "analytical"]),
  contactQuality: z.number().min(0).max(100),
  roleClarity: z.number().min(0).max(100),
  staffTrust: z.number().min(0).max(100),
  visitStatus: z.enum(["none", "invited", "scheduled", "completed"]),
  officialVisit: z.object({
    id: z.string().min(1),
    status: z.enum(["scheduled", "completed"]),
    scheduledWeek: z.number().int().nonnegative(),
    scheduledDate: gameDateSchema,
    dueCompletedDay: z.number().int().nonnegative(),
    completedWeek: z.number().int().nonnegative().optional(),
    completedDate: gameDateSchema.optional(),
    campusFit: z.number().min(0).max(100).optional(),
    staffConnection: z.number().min(0).max(100).optional(),
    roleClarity: z.number().min(0).max(100).optional(),
    familyComfort: z.number().min(0).max(100).optional(),
    overallImpression: z.number().min(0).max(100).optional(),
    summary: z.string().min(2).optional(),
    warning: z.string().min(2).optional(),
  }).optional(),
  promises: z.array(z.object({
    id: z.string().min(1),
    category: z.enum(["role", "development", "scheme", "stability"]),
    statement: z.string().min(2),
    credibility: z.number().min(0).max(100),
    source: z.enum(["recruiter-call", "official-visit"]),
    madeWeek: z.number().int().nonnegative(),
  })),
  playerRead: z.string().min(2),
  evaluation: z.string().min(2),
  lastUpdate: z.string().min(2),
  offer: z.object({
    id: z.string().min(1),
    issuedWeek: z.number().int().nonnegative(),
    scholarship: z.literal("full"),
    projectedRole: projectedCollegeRoleSchema,
    expiresAfterWeek: z.number().int().min(1),
  }).optional(),
});
const footballRecruitingSchema = z.object({
  moduleVersion: z.literal(2),
  visibility: z.number().min(0).max(100),
  filmGrade: z.number().min(0).max(100),
  consistency: z.number().min(0).max(100),
  healthConfidence: z.number().min(0).max(100),
  academicClearance: z.number().min(0).max(100),
  coachRecommendation: z.number().min(0).max(100),
  competitionLevel: z.number().min(0).max(100),
  regionalRankLabel: z.string().min(2),
  interestedPrograms: z.number().int().nonnegative(),
  offers: z.number().int().nonnegative(),
  actionWeek: z.number().int().nonnegative(),
  actionsUsed: z.number().int().nonnegative().max(2),
  decommitments: z.number().int().nonnegative(),
  commitment: z.object({
    programId: z.string().min(1),
    status: z.enum(["verbal", "signed"]),
    committedWeek: z.number().int().nonnegative(),
    committedDate: gameDateSchema,
    confidence: z.number().min(0).max(100),
    signedDate: gameDateSchema.optional(),
    entryRoute: z.enum(["scholarship", "preferred-walk-on"]).optional(),
  }).optional(),
  programs: z.array(recruitingProgramSchema).min(20),
  activity: z.array(z.object({
    id: z.string().min(1),
    week: z.number().int().nonnegative(),
    programId: z.string().min(1).optional(),
    date: gameDateSchema,
    kind: z.enum(["evaluation", "contact", "action", "offer", "cooling", "conversation", "visit", "commitment", "signing", "expiration"]),
    title: z.string().min(2),
    detail: z.string().min(2),
  })),
});


const collegeHeroRoleSchema = z.enum(["starter", "rotation", "special-teams", "developmental"]);
const collegeHeroDecisionSchema = z.object({
  id: z.string().min(1),
  kind: z.enum(["coach-meeting", "position-rivalry", "transfer-window"]),
  createdWeek: z.number().int().min(1),
  title: z.string().min(2),
  detail: z.string().min(2),
  options: z.array(z.object({
    id: z.string().min(1),
    label: z.string().min(2),
    detail: z.string().min(2),
  })).min(2),
});
const collegeHeroCareerSchema = z.object({
  version: z.literal(1),
  teamId: z.string().min(1),
  seasonYear: z.number().int(),
  week: z.number().int().min(1),
  role: collegeHeroRoleSchema,
  depthRank: z.number().int().min(1),
  coachTrust: z.number().min(0).max(100),
  lockerRoomStanding: z.number().min(0).max(100),
  practiceReps: z.number().min(0).max(100),
  weeklyPracticeGrade: z.enum(["A", "B", "C", "D"]),
  seasonSnaps: z.number().int().nonnegative(),
  gamesPlayed: z.number().int().nonnegative(),
  starts: z.number().int().nonnegative(),
  redshirtStatus: z.enum(["active", "candidate", "used"]),
  transferIntent: z.enum(["stay", "open", "portal"]),
  promises: z.array(z.object({
    id: z.string().min(1),
    kind: z.literal("playing-time"),
    targetRole: projectedCollegeRoleSchema,
    madeWeek: z.number().int().min(1),
    deadlineWeek: z.number().int().min(1),
    status: z.enum(["active", "kept", "broken"]),
    summary: z.string().min(2),
  })),
  pendingDecision: collegeHeroDecisionSchema.optional(),
  gameLog: z.array(z.object({
    id: z.string().min(1),
    seasonYear: z.number().int(),
    week: z.number().int().min(1),
    opponentId: z.string().min(1),
    opponentName: z.string().min(1),
    won: z.boolean(),
    score: z.string().min(3),
    snaps: z.number().int().nonnegative(),
    started: z.boolean(),
    grade: z.enum(["A", "B", "C", "D"]),
    role: collegeHeroRoleSchema,
  })),
  weekLog: z.array(z.object({
    id: z.string().min(1),
    seasonYear: z.number().int(),
    week: z.number().int().min(1),
    role: collegeHeroRoleSchema,
    depthRank: z.number().int().min(1),
    coachTrust: z.number().min(0).max(100),
    lockerRoomStanding: z.number().min(0).max(100),
    practiceGrade: z.enum(["A", "B", "C", "D"]),
    summary: z.string().min(2),
  })),
  lastSummary: z.string().min(2),
});

const footballCollegeSchema = z.object({
  moduleVersion: z.literal(1),
  status: z.enum(["high-school", "signed", "orientation", "active"]),
  entryRoute: z.enum(["scholarship", "preferred-walk-on"]).optional(),
  signedProgramId: z.string().min(1).optional(),
  signedDate: gameDateSchema.optional(),
  program: z.object({
    id: z.string().min(1),
    name: z.string().min(2),
    shortName: z.string().min(2),
    city: z.string().min(2),
    stateCode: z.string().length(2),
    tier: recruitingProgramTierSchema,
    prestige: z.number().min(0).max(100),
    scheme: z.string().min(2),
    medicine: z.number().min(0).max(100),
    facilities: z.number().min(0).max(100),
    youthOpportunity: z.number().min(0).max(100),
    headCoachName: z.string().min(2),
    recruiterName: z.string().min(2),
  }).optional(),
  positionRoom: z.array(z.object({
    id: z.string().min(1),
    name: z.string().min(2),
    year: z.enum(["Freshman", "Sophomore", "Junior", "Senior"]),
    overall: z.number().min(0).max(100),
    style: z.string().min(2),
    redshirt: z.boolean(),
    depthRank: z.number().int().nonnegative(),
    isHero: z.boolean(),
  })),
  depthRank: z.number().int().min(1).optional(),
  projectedRole: projectedCollegeRoleSchema.optional(),
  actualRole: projectedCollegeRoleSchema.optional(),
  promiseVerdict: z.enum(["kept", "uncertain", "misleading"]).optional(),
  promiseSummary: z.string().min(2).optional(),
  offseason: z.object({
    startDate: gameDateSchema,
    arrivalDate: gameDateSchema,
    trainingGrade: z.enum(["A", "B", "C", "D"]),
    overallDelta: z.number(),
    weightDelta: z.number(),
    gpaDelta: z.number(),
    healthDelta: z.number(),
    confidenceDelta: z.number(),
    summary: z.string().min(2),
  }).optional(),
  arrivalDate: gameDateSchema.optional(),
  onboardingPriority: z.enum(["compete-now", "learn-system", "academic-base"]).optional(),
  heroCareer: collegeHeroCareerSchema.optional(),
});

const footballSchema = z.object({
  moduleVersion: z.literal(8),
  worldSeed: z.string().min(1),
  stage: z.enum(["high-school-preseason", "college-orientation", "college-season"]),
  position: z.enum(["QB", "RB", "WR", "LB", "CB"]),
  archetypeId: z.string().min(1),
  archetypeName: z.string().min(1),
  jerseyNumber: z.number().int().min(0).max(99),
  ratings: z.object({
    overall: z.number().min(0).max(100),
    potentialBand: z.enum(["role-player", "starter", "high-upside", "national-ceiling"]),
    athleticism: z.number().min(0).max(100),
    technique: z.number().min(0).max(100),
    footballIq: z.number().min(0).max(100),
    competitiveness: z.number().min(0).max(100),
  }),
  school: schoolSchema,
  staff: z.object({
    headCoach: coachSchema,
    positionCoach: coachSchema,
    offensiveCoordinator: coachSchema,
    defensiveCoordinator: coachSchema,
  }),
  roster: z.array(rosterPlayerSchema).min(35),
  teamDynamics: z.object({
    morale: z.number().min(0).max(100),
    cohesion: z.number().min(0).max(100),
    discipline: z.number().min(0).max(100),
    schemeMastery: z.number().min(0).max(100),
  }),
  training: footballTrainingSchema,
  match: footballMatchSchema,
  depthChart: z.object({
    rank: z.number().int().min(1),
    playersAtPosition: z.number().int().min(1),
    coachTrust: z.number().min(0).max(100),
    projectedRole: z.enum(["starter", "rotation", "special-teams", "developmental"]),
    directRival: z.object({
      id: z.string().min(1),
      name: z.string().min(3),
      year: playerYearSchema,
      overall: z.number().min(0).max(100),
      style: z.string().min(2),
    }),
    evaluation: depthEvaluationSchema,
    lastDecision: depthDecisionSchema,
  }),
  season: z.object({
    year: z.number().int().min(2000),
    phase: z.enum(["regular-season", "complete"]),
    week: z.number().int().nonnegative(),
    wins: z.number().int().nonnegative(),
    losses: z.number().int().nonnegative(),
    nextOpponent: z.object({
      id: z.string().min(1),
      name: z.string().min(2),
      record: z.string().min(1),
      threat: z.string().min(2),
    }),
    totalWeeks: z.number().int().min(1),
    opponents: z.array(z.object({
      id: z.string().min(1),
      name: z.string().min(2),
      shortName: z.string().min(1),
      mascot: z.string().min(2),
      city: z.string().min(2),
      stateCode: z.string().length(2),
      rating: z.number().min(0).max(100),
      offenseStyle: z.string().min(2),
      defenseStyle: z.string().min(2),
      strength: z.string().min(2),
      weakness: z.string().min(2),
      keyPlayer: z.string().min(2),
      scoutConfidence: z.number().min(0).max(100),
    })).min(1),
    schedule: z.array(z.object({
      id: z.string().min(1),
      week: z.number().int().min(1),
      date: gameDateSchema,
      home: z.boolean(),
      opponentId: z.string().min(1),
      opponentName: z.string().min(2),
      opponentShortName: z.string().min(1),
      opponentRating: z.number().min(0).max(100),
      status: z.enum(["scheduled", "complete"]),
      heroScore: z.number().int().nonnegative().optional(),
      opponentScore: z.number().int().nonnegative().optional(),
      won: z.boolean().optional(),
      heroGrade: z.enum(["A", "B", "C", "D"]).optional(),
      spotlight: z.string().min(2).optional(),
    })).min(1),
    standings: z.array(z.object({
      teamId: z.string().min(1),
      name: z.string().min(2),
      shortName: z.string().min(1),
      rating: z.number().min(0).max(100),
      wins: z.number().int().nonnegative(),
      losses: z.number().int().nonnegative(),
      pointsFor: z.number().int().nonnegative(),
      pointsAgainst: z.number().int().nonnegative(),
      streak: z.number().int(),
      isHeroTeam: z.boolean(),
    })).min(2),
    heroTotals: matchStatLineSchema,
    awards: z.array(z.object({
      id: z.string().min(1),
      week: z.number().int().min(1),
      title: z.string().min(2),
      playerName: z.string().min(2),
      teamName: z.string().min(1),
      detail: z.string().min(2),
      isHero: z.boolean(),
    })),
    teamLeaders: z.array(z.object({
      id: z.string().min(1),
      name: z.string().min(2),
      position: z.string().min(1),
      category: z.string().min(2),
      value: z.string().min(1),
    })),
  }),
  recruitment: footballRecruitingSchema,
  college: footballCollegeSchema,
});

const focusSchema = z.object({
  training: z.number().min(0).max(100),
  recovery: z.number().min(0).max(100),
  study: z.number().min(0).max(100),
  social: z.number().min(0).max(100),
});

const dayDeltaSchema = z.object({
  energy: z.number(),
  fatigue: z.number(),
  stress: z.number(),
  confidence: z.number(),
  health: z.number(),
  gpa: z.number(),
  coachTrust: z.number(),
  overall: z.number(),
});

const dayOutcomeSchema = z.object({
  id: z.string().min(1),
  date: gameDateSchema,
  grade: z.enum(["A", "B", "C", "D"]),
  title: z.string().min(1),
  summary: z.string().min(1),
  highlights: z.array(z.string().min(1)),
  deltas: dayDeltaSchema,
});

const lifeSchema = z.object({
  moduleVersion: z.literal(1),
  weekNumber: z.number().int().min(1),
  dayIndex: z.number().int().min(0).max(6),
  completedDays: z.number().int().nonnegative(),
  weeklyPlan: z.object({
    templateId: z.enum(["balanced", "breakout", "recovery", "academic", "film-room"]),
    intensity: z.enum(["controlled", "standard", "aggressive"]),
    focus: focusSchema,
    revision: z.number().int().min(1),
  }),
  consistency: z.number().min(0).max(100),
  lastOutcome: dayOutcomeSchema.optional(),
});


const relationshipMemorySchema = z.object({
  id: z.string().min(1),
  date: gameDateSchema,
  summary: z.string().min(2),
  impact: z.number().min(-100).max(100),
  importance: z.union([z.literal(1), z.literal(2), z.literal(3), z.literal(4), z.literal(5)]),
});

const relationshipNpcSchema = z.object({
  id: z.string().min(1),
  seed: z.string().min(1),
  linkedEntityId: z.string().min(1).optional(),
  name: z.string().min(2),
  age: z.number().int().min(14).max(90),
  role: z.enum(["guardian", "head-coach", "position-coach", "rival", "teammate", "counselor", "reporter"]),
  group: z.enum(["family", "team", "school", "media"]),
  relationship: z.number().min(-100).max(100),
  temperament: z.enum(["direct", "reserved", "volatile", "warm", "calculating", "demanding"]),
  goal: z.string().min(2),
  fear: z.string().min(2),
  currentSituation: z.string().min(2),
  status: z.enum(["steady", "under-pressure", "hopeful", "frustrated", "focused", "concerned"]),
  memories: z.array(relationshipMemorySchema),
});

const relationshipEffectSchema = z.object({
  relationship: z.number().min(-100).max(100),
  coachTrust: z.number().optional(),
  confidence: z.number().optional(),
  stress: z.number().optional(),
  energy: z.number().optional(),
  gpa: z.number().optional(),
  visibility: z.number().optional(),
  teamMorale: z.number().optional(),
});

const relationshipEventTypeSchema = z.enum([
  "coach-accountability",
  "coach-plan-review",
  "rival-pressure",
  "family-academics",
  "family-check-in",
  "teammate-film",
  "counselor-warning",
  "reporter-spotlight",
]);

const relationshipEventSchema = z.object({
  id: z.string().min(1),
  type: relationshipEventTypeSchema,
  createdOn: gameDateSchema,
  title: z.string().min(2),
  scene: z.string().min(2),
  context: z.array(z.string().min(2)).min(1),
  participantIds: z.array(z.string().min(1)).min(1),
  primaryNpcId: z.string().min(1),
  options: z.array(z.object({
    id: z.string().min(1),
    label: z.string().min(2),
    detail: z.string().min(2),
    tone: z.enum(["calm", "firm", "defensive", "open"]),
    effects: relationshipEffectSchema,
    memory: z.string().min(2),
    outcome: z.string().min(2),
    followUp: z.object({ type: relationshipEventTypeSchema, delayDays: z.number().int().min(1) }).optional(),
  })).min(2).max(4),
});

const relationshipsSchema = z.object({
  moduleVersion: z.literal(1),
  npcs: z.array(relationshipNpcSchema).min(4),
  pendingEvent: relationshipEventSchema.optional(),
  resolvedEvents: z.array(z.object({
    id: z.string().min(1),
    type: relationshipEventTypeSchema,
    title: z.string().min(2),
    resolvedOn: gameDateSchema,
    resolvedAtCompletedDay: z.number().int().nonnegative(),
    primaryNpcId: z.string().min(1),
    optionId: z.string().min(1),
    outcome: z.string().min(2),
    relationshipDelta: z.number().min(-100).max(100),
  })),
  queuedEvents: z.array(z.object({
    id: z.string().min(1),
    type: relationshipEventTypeSchema,
    dueCompletedDay: z.number().int().nonnegative(),
    primaryNpcId: z.string().min(1),
  })),
  lastGeneratedCompletedDay: z.number().int().min(-1),
});

const ecosystemPositionNeedsSchema = z.object({
  QB: z.number().min(0).max(100),
  RB: z.number().min(0).max(100),
  WR: z.number().min(0).max(100),
  LB: z.number().min(0).max(100),
  CB: z.number().min(0).max(100),
});

const worldConstitutionSchema = z.object({
  version: z.literal(1),
  modernEligibilityStartYear: z.number().int().min(2020).max(2200),
  ageBasedEligibilityYears: z.number().int().min(1).max(10),
  legacyCompetitionSeasons: z.number().int().min(1).max(10),
  legacyEligibilityWindowYears: z.number().int().min(1).max(10),
  legacyRedshirtGameLimit: z.number().int().min(0).max(20),
  collegeRosterLimit: z.number().int().min(1).max(200),
  collegeScholarshipLimit: z.number().int().min(0).max(200),
  minimumTermCredits: z.number().min(0).max(30),
  degreeProgressBenchmarks: z.object({
    endOfYearTwo: z.number().min(0).max(100),
    endOfYearThree: z.number().min(0).max(100),
    endOfYearFour: z.number().min(0).max(100),
  }),
  simulationOrder: z.tuple([
    z.literal("calendar"),
    z.literal("eligibility"),
    z.literal("rosters"),
    z.literal("teams"),
    z.literal("competition"),
    z.literal("recruiting"),
    z.literal("movement"),
    z.literal("history"),
  ]),
});

const worldCycleSchema = z.object({
  academicYear: z.number().int().min(2020).max(2200),
  seasonYear: z.number().int().min(2020).max(2200),
  phase: z.enum(["summer-recruiting", "preseason", "regular-season", "postseason", "winter-evaluation", "spring-development"]),
  phaseWeek: z.number().int().min(1).max(30),
});

const ecosystemTeamComplianceSchema = z.object({
  rosterLimit: z.number().int().min(1).max(200),
  scholarshipLimit: z.number().int().min(0).max(200),
  fundedScholarships: z.number().int().min(0).max(200),
  estimatedRosterSize: z.number().int().min(0).max(200),
  scholarshipsUsed: z.number().int().min(0).max(200),
  academicSupport: z.number().min(0).max(100),
  status: z.enum(["clear", "warning", "violation"]),
});

const ecosystemProgramResourcesSchema = z.object({
  tier: z.enum(["local", "regional", "power", "elite"]),
  annualBudget: z.number().min(0),
  footballBudget: z.number().min(0),
  coachingBudget: z.number().min(0),
  recruitingBudget: z.number().min(0),
  medicalBudget: z.number().min(0),
  facilitiesBudget: z.number().min(0),
  academicBudget: z.number().min(0),
  nilCapacity: z.number().min(0),
  donorSupport: z.number().min(0).max(100),
  mediaRevenue: z.number().min(0),
  currentBalance: z.number(),
  recruitingCommitted: z.number().min(0),
  medicalCommitted: z.number().min(0),
  nilCommitted: z.number().min(0),
  facilitiesLevel: z.number().min(0).max(100),
  medicalLevel: z.number().min(0).max(100),
  academicSupportLevel: z.number().min(0).max(100),
  donorConfidence: z.number().min(0).max(100),
  boardPatience: z.number().min(0).max(100),
  financialPressure: z.number().min(0).max(100),
  spendingPriority: z.enum(["balanced", "recruiting", "development", "medical", "facilities"]),
  lastBudgetYear: z.number().int().min(2020).max(2200),
});

const ecosystemPlayerEligibilitySchema = z.object({
  model: z.enum(["high-school", "legacy-four-in-five", "age-based-five-year"]),
  initialEnrollmentYear: z.number().int().min(2020).max(2200),
  windowStartYear: z.number().int().min(2020).max(2200),
  windowEndYear: z.number().int().min(2020).max(2200),
  athleticallyEligible: z.boolean(),
  academicStanding: z.enum(["good", "warning", "ineligible"]),
  termCredits: z.number().min(0).max(30),
  degreeProgress: z.number().min(0).max(100),
  gamesPlayedThisSeason: z.number().int().min(0).max(30),
  redshirtUsed: z.boolean(),
  scholarshipStatus: z.enum(["none", "partial", "full"]),
});

const ecosystemTalentProfileSchema = z.object({
  regionId: z.string().min(1),
  homeState: z.string().length(2),
  graduationYear: z.number().int().min(2020).max(2200),
  route: z.enum(["traditional", "multi-sport", "late-bloomer", "juco", "walk-on"]),
  developmentCurve: z.enum(["early", "steady", "late"]),
  physicalMaturity: z.number().min(0).max(100),
  scoutingGrade: z.number().min(0).max(100),
  campExposure: z.number().min(0).max(100),
  exposure: z.enum(["hidden", "local", "regional", "national"]),
  academicProjection: z.number().min(0).max(100),
  discoveredYear: z.number().int().min(2020).max(2200),
});

const ecosystemTalentPipelineSchema = z.object({
  version: z.literal(1),
  generationYear: z.number().int().min(2020).max(2200),
  regions: z.array(z.object({
    id: z.string().min(1), name: z.string().min(2), stateCodes: z.array(z.string().length(2)).min(1),
    populationWeight: z.number().min(0).max(100), footballCulture: z.number().min(0).max(100),
    infrastructure: z.number().min(0).max(100), exposureBias: z.number().min(0).max(100),
    academicAccess: z.number().min(0).max(100), annualClassSize: z.number().int().positive(),
  })).min(4),
  camps: z.array(z.object({
    id: z.string().min(1), name: z.string().min(2), regionId: z.string().min(1),
    phase: z.enum(["summer-recruiting", "spring-development"]),
    phaseWeek: z.number().int().min(1).max(30), prestige: z.number().min(0).max(100),
    capacity: z.number().int().positive(), lastHeldSeasonYear: z.number().int().min(2019).max(2200),
  })),
  independentProspects: z.array(z.object({
    id: z.string().min(1), seed: z.string().min(1), name: z.string().min(2),
    age: z.number().int().min(17).max(23), position: z.enum(["QB", "RB", "WR", "LB", "CB"]),
    route: z.enum(["juco", "walk-on"]), regionId: z.string().min(1), homeState: z.string().length(2),
    overall: z.number().min(0).max(100), potential: z.number().min(0).max(100), health: z.number().min(0).max(100),
    academicProjection: z.number().min(0).max(100), exposure: z.enum(["hidden", "local", "regional", "national"]),
    campExposure: z.number().min(0).max(100), graduationYear: z.number().int().min(2020).max(2200),
    yearsInRoute: z.number().int().min(0).max(4), status: z.enum(["available", "contacted", "committed"]),
    committedTeamId: z.string().min(1).optional(),
  })),
  classHistory: z.array(z.object({
    seasonYear: z.number().int().min(2020).max(2200), generatedPlayers: z.number().int().nonnegative(),
    traditionalPlayers: z.number().int().nonnegative(), multiSportPlayers: z.number().int().nonnegative(),
    lateBloomers: z.number().int().nonnegative(), jucoEntries: z.number().int().nonnegative(),
    walkOnEntries: z.number().int().nonnegative(), topProspectIds: z.array(z.string().min(1)),
  })),
});

const ecosystemPositionProjectionSchema = z.object({
  position: z.enum(["QB", "RB", "WR", "LB", "CB"]),
  currentPlayers: z.number().int().nonnegative(),
  returningNextYear: z.number().int().nonnegative(),
  returningInTwoYears: z.number().int().nonnegative(),
  projectedDepartures: z.number().int().nonnegative(),
  scholarshipPlayers: z.number().int().nonnegative(),
  averageOverall: z.number().min(0).max(100),
  bestOverall: z.number().min(0).max(100),
  averagePotential: z.number().min(0).max(100),
  needNow: z.number().min(0).max(100),
  needNextYear: z.number().min(0).max(100),
  targetAdds: z.number().int().min(0).max(3),
});

const ecosystemRosterPlanSchema = z.object({
  version: z.literal(1),
  seasonYear: z.number().int().min(2020).max(2200),
  reviewedWeek: z.number().int().nonnegative(),
  strategy: z.enum(["contend", "balanced", "develop", "rebuild"]),
  planningHorizonYears: z.literal(3),
  targetClassSize: z.number().int().nonnegative().max(28),
  availableRosterSpots: z.number().int().nonnegative(),
  availableScholarships: z.number().int().nonnegative(),
  projectedDepartures: z.number().int().nonnegative(),
  retentionRisk: z.number().min(0).max(100),
  redshirtPlayerIds: z.array(z.string().min(1)),
  developmentalPlayerIds: z.array(z.string().min(1)),
  positionChanges: z.array(z.object({
    playerId: z.string().min(1),
    fromPosition: z.enum(["QB", "RB", "WR", "LB", "CB"]),
    toPosition: z.enum(["QB", "RB", "WR", "LB", "CB"]),
    reason: z.string().min(2),
    applied: z.boolean(),
  })),
  scholarshipDecisions: z.array(z.object({
    playerId: z.string().min(1),
    previousStatus: z.enum(["none", "partial", "full"]),
    nextStatus: z.enum(["partial", "full"]),
    reason: z.string().min(2),
  })),
  positionProjections: z.object({
    QB: ecosystemPositionProjectionSchema,
    RB: ecosystemPositionProjectionSchema,
    WR: ecosystemPositionProjectionSchema,
    LB: ecosystemPositionProjectionSchema,
    CB: ecosystemPositionProjectionSchema,
  }),
  lastReviewReason: z.string().min(2),
});


const ecosystemMovementMarketSchema = z.object({
  version: z.literal(1),
  seasonYear: z.number().int().min(2020).max(2200),
  lastProcessedDay: z.number().int().nonnegative(),
  openings: z.array(z.object({
    id: z.string().min(1),
    teamId: z.string().min(1),
    position: z.enum(["QB", "RB", "WR", "LB", "CB"]),
    seasonYear: z.number().int().min(2020).max(2200),
    slots: z.number().int().nonnegative(),
    scholarshipSlots: z.number().int().nonnegative(),
    nilAvailable: z.number().min(0),
    recruitingAvailable: z.number().min(0),
    filledByCandidateIds: z.array(z.string().min(1)),
    status: z.enum(["open", "filled", "closed"]),
    reason: z.string().min(2),
  })),
  negotiations: z.array(z.object({
    id: z.string().min(1),
    candidateId: z.string().min(1),
    candidateKind: z.enum(["high-school", "juco", "walk-on", "transfer"]),
    candidateName: z.string().min(2),
    position: z.enum(["QB", "RB", "WR", "LB", "CB"]),
    teamId: z.string().min(1),
    status: z.enum(["offered", "accepted", "withdrawn", "expired"]),
    scholarship: z.enum(["none", "partial", "full"]),
    nilOffer: z.number().min(0),
    promisedRole: z.enum(["starter-path", "rotation", "developmental"]),
    score: z.number().min(0).max(100),
    createdWeek: z.number().int().min(1),
    expiresWeek: z.number().int().min(1),
    reason: z.string().min(2),
  })),
  coachVacancies: z.array(z.object({
    id: z.string().min(1),
    teamId: z.string().min(1),
    role: z.enum(["head-coach", "coordinator"]),
    status: z.enum(["open", "filled", "cancelled"]),
    openedSeasonYear: z.number().int().min(2020).max(2200),
    openedWeek: z.number().int().min(1),
    salaryBudget: z.number().min(0),
    reason: z.string().min(2),
    formerCoachId: z.string().min(1).optional(),
    hiredCoachId: z.string().min(1).optional(),
  })),
  acceptedMoves: z.number().int().nonnegative(),
  withdrawnOffers: z.number().int().nonnegative(),
  digest: z.array(z.string().min(2)).max(6),
});


const ecosystemCompetitionGameSchema = z.object({
  id: z.string().min(1),
  seasonYear: z.number().int().min(2020).max(2200),
  week: z.number().int().min(1).max(20),
  kind: z.enum(["conference", "nonconference", "rivalry", "conference-championship", "playoff", "bowl"]),
  homeTeamId: z.string().min(1),
  awayTeamId: z.string().min(1),
  neutralSite: z.boolean(),
  conferenceGame: z.boolean(),
  rivalryId: z.string().min(1).optional(),
  status: z.enum(["scheduled", "complete"]),
  homeScore: z.number().int().nonnegative().optional(),
  awayScore: z.number().int().nonnegative().optional(),
  winnerTeamId: z.string().min(1).optional(),
  loserTeamId: z.string().min(1).optional(),
  upset: z.boolean().optional(),
});

const ecosystemNationalRankingSchema = z.object({
  seasonYear: z.number().int().min(2020).max(2200),
  week: z.number().int().nonnegative().max(20),
  teamId: z.string().min(1),
  rank: z.number().int().min(1),
  previousRank: z.number().int().min(1).optional(),
  score: z.number().min(0).max(100),
  strengthOfSchedule: z.number().min(0).max(100),
  qualityWins: z.number().int().nonnegative(),
  pointDifferential: z.number().int(),
});

const ecosystemCompetitionSchema = z.object({
  version: z.literal(1),
  seasonYear: z.number().int().min(2020).max(2200),
  schedule: z.array(ecosystemCompetitionGameSchema),
  rankings: z.array(ecosystemNationalRankingSchema),
  rankingHistory: z.array(z.object({
    seasonYear: z.number().int().min(2020).max(2200),
    week: z.number().int().nonnegative().max(20),
    rankings: z.array(ecosystemNationalRankingSchema),
  })),
  playoff: z.object({
    seasonYear: z.number().int().min(2020).max(2200),
    stage: z.enum(["regular-season", "conference-championships", "quarterfinals", "semifinals", "national-championship", "complete"]),
    seedTeamIds: z.array(z.string().min(1)),
    gameIds: z.array(z.string().min(1)),
    championTeamId: z.string().min(1).optional(),
  }),
  awards: z.array(z.object({
    id: z.string().min(1),
    seasonYear: z.number().int().min(2020).max(2200),
    week: z.number().int().min(1).max(20).optional(),
    kind: z.enum(["player-of-week", "conference-player", "national-player", "position-award", "all-american"]),
    playerId: z.string().min(1),
    teamId: z.string().min(1),
    title: z.string().min(2),
    detail: z.string().min(2),
  })),
  rivalries: z.array(z.object({
    id: z.string().min(1),
    name: z.string().min(2),
    teamAId: z.string().min(1),
    teamBId: z.string().min(1),
    intensity: z.number().min(0).max(100),
    meetings: z.number().int().nonnegative(),
    winsA: z.number().int().nonnegative(),
    winsB: z.number().int().nonnegative(),
    ties: z.number().int().nonnegative(),
    streak: z.number().int().nonnegative(),
    lastWinnerTeamId: z.string().min(1).optional(),
  })),
  programLegacies: z.array(z.object({
    teamId: z.string().min(1),
    allTimeWins: z.number().int().nonnegative(),
    allTimeLosses: z.number().int().nonnegative(),
    nationalTitles: z.number().int().nonnegative(),
    playoffAppearances: z.number().int().nonnegative(),
    bowlWins: z.number().int().nonnegative(),
    rivalryWins: z.number().int().nonnegative(),
    bestRank: z.number().int().min(1),
    reputation: z.number().min(0).max(100),
    eraLabel: z.enum(["unknown", "building", "contender", "power", "dynasty", "decline"]),
  })),
  digest: z.array(z.string().min(2)).max(6),
});

const ecosystemPositionRoleSchema = z.enum([
  "pocket-distributor", "dual-threat", "field-general",
  "zone-runner", "power-back", "receiving-back",
  "separator", "vertical-threat", "possession-target",
  "run-anchor", "coverage-backer", "edge-blitzer",
  "press-corner", "zone-corner", "ball-hawk",
]);

const ecosystemTacticalIdentitySchema = z.object({
  version: z.literal(1),
  offenseSystem: z.enum(["air-raid", "west-coast", "power-run", "spread-option", "multiple"]),
  defenseSystem: z.enum(["quarters-425", "multiple-34", "over-43", "nickel-match", "man-pressure", "multiple-defense"]),
  tempo: z.enum(["controlled", "balanced", "fast"]),
  offensiveAggression: z.enum(["conservative", "balanced", "aggressive"]),
  defensiveAggression: z.enum(["conservative", "balanced", "aggressive"]),
  complexity: z.number().min(0).max(100),
  installation: z.number().min(0).max(100),
  continuity: z.number().min(0).max(100),
  rotationDepth: z.number().min(0).max(100),
  headCoachFingerprint: z.string().min(1),
  positionRoles: z.object({
    QB: z.object({ primary: ecosystemPositionRoleSchema, secondary: ecosystemPositionRoleSchema }),
    RB: z.object({ primary: ecosystemPositionRoleSchema, secondary: ecosystemPositionRoleSchema }),
    WR: z.object({ primary: ecosystemPositionRoleSchema, secondary: ecosystemPositionRoleSchema }),
    LB: z.object({ primary: ecosystemPositionRoleSchema, secondary: ecosystemPositionRoleSchema }),
    CB: z.object({ primary: ecosystemPositionRoleSchema, secondary: ecosystemPositionRoleSchema }),
  }),
});

const ecosystemPlayerTacticalProfileSchema = z.object({
  version: z.literal(1),
  archetype: ecosystemPositionRoleSchema,
  preferredRole: ecosystemPositionRoleSchema,
  secondaryRole: ecosystemPositionRoleSchema,
  schemeFit: z.number().min(0).max(100),
  roleFit: z.number().min(0).max(100),
  learning: z.number().min(0).max(100),
  versatility: z.number().min(0).max(100),
  lastEvaluatedSeason: z.number().int().min(0).max(2200),
  lastCoachFingerprint: z.string().min(1).optional(),
});


const ecosystemSocialSchema = z.object({
  version: z.literal(1),
  seasonYear: z.number().int().min(2020).max(2200),
  lastProcessedDay: z.number().int().nonnegative(),
  bonds: z.array(z.object({
    id: z.string().min(1),
    entityAId: z.string().min(1),
    entityBId: z.string().min(1),
    entityAKind: z.enum(["player", "coach"]),
    entityBKind: z.enum(["player", "coach"]),
    teamId: z.string().min(1).optional(),
    kind: z.enum(["teammate", "position-rival", "mentor", "coach-player", "staff"]),
    trust: z.number().min(0).max(100),
    respect: z.number().min(0).max(100),
    chemistry: z.number().min(0).max(100),
    tension: z.number().min(0).max(100),
    influence: z.number().min(0).max(100),
    familiarityWeeks: z.number().int().nonnegative().max(999),
    active: z.boolean(),
    lastSeasonYear: z.number().int().min(2020).max(2200),
    lastWeek: z.number().int().min(1).max(60),
  })).max(3000),
  teamCultures: z.array(z.object({
    teamId: z.string().min(1),
    cohesion: z.number().min(0).max(100),
    accountability: z.number().min(0).max(100),
    coachTrust: z.number().min(0).max(100),
    leadership: z.number().min(0).max(100),
    conflict: z.number().min(0).max(100),
    morale: z.number().min(0).max(100),
    stability: z.number().min(0).max(100),
    lastSeasonYear: z.number().int().min(2020).max(2200),
    lastWeek: z.number().int().min(1).max(60),
  })),
  incidents: z.array(z.object({
    id: z.string().min(1),
    kind: z.enum(["mentorship", "locker-room-conflict", "leadership", "reconciliation", "staff-friction", "broken-promise"]),
    seasonYear: z.number().int().min(2020).max(2200),
    week: z.number().int().min(1).max(60),
    teamId: z.string().min(1),
    participantIds: z.array(z.string().min(1)).min(1),
    title: z.string().min(2),
    detail: z.string().min(2),
    impact: z.number().min(-10).max(10),
  })).max(180),
  digest: z.array(z.string().min(2)).max(6),
});

const footballEcosystemSchema = z.object({
  moduleVersion: z.literal(10),
  constitution: worldConstitutionSchema,
  cycle: worldCycleSchema,
  lastSimulatedDay: z.number().int().nonnegative(),
  currentWeek: z.number().int().min(1),
  lastUpdatedOn: gameDateSchema,
  seasonYear: z.number().int().min(2020).max(2200),
  seasonWeek: z.number().int().min(1).max(20),
  phase: z.enum(["regular-season", "postseason", "offseason"]),
  lastOffseasonYear: z.number().int().min(2019).max(2200),
  conferences: z.array(z.object({
    id: z.string().min(1),
    name: z.string().min(2),
    shortName: z.string().min(1),
    region: z.string().min(2),
    prestige: z.number().min(0).max(100),
    teamIds: z.array(z.string().min(1)).min(2),
    champions: z.array(z.object({ seasonYear: z.number().int(), teamId: z.string().min(1) })),
  })).min(2),
  teams: z.array(z.object({
    id: z.string().min(1),
    seed: z.string().min(1),
    name: z.string().min(2),
    shortName: z.string().min(1),
    level: z.enum(["high-school", "college"]),
    stateCode: z.string().length(2),
    conferenceId: z.string().min(1).optional(),
    prestige: z.number().min(0).max(100),
    rating: z.number().min(0).max(100),
    expectation: z.number().min(0).max(100),
    wins: z.number().int().nonnegative(),
    losses: z.number().int().nonnegative(),
    conferenceWins: z.number().int().nonnegative(),
    conferenceLosses: z.number().int().nonnegative(),
    streak: z.number().int(),
    championships: z.number().int().nonnegative(),
    offenseStyle: z.string().min(2),
    defenseStyle: z.string().min(2),
    positionNeeds: ecosystemPositionNeedsSchema,
    rosterIds: z.array(z.string().min(1)),
    coachIds: z.array(z.string().min(1)),
    trend: z.enum(["rising", "stable", "falling"]),
    compliance: ecosystemTeamComplianceSchema,
    resources: ecosystemProgramResourcesSchema,
    rosterPlan: ecosystemRosterPlanSchema,
    tactical: ecosystemTacticalIdentitySchema,
  })).min(10),
  players: z.array(z.object({
    id: z.string().min(1),
    seed: z.string().min(1),
    name: z.string().min(2),
    teamId: z.string().min(1),
    level: z.enum(["high-school", "college"]),
    age: z.number().int().min(14).max(24),
    classYear: z.enum(["Freshman", "Sophomore", "Junior", "Senior"]),
    position: z.enum(["QB", "RB", "WR", "LB", "CB"]),
    overall: z.number().min(0).max(100),
    potential: z.number().min(0).max(100),
    health: z.number().min(0).max(100),
    form: z.number().min(0).max(100),
    status: z.enum(["starter", "rotation", "backup", "injured"]),
    depthRank: z.number().int().min(1),
    trajectory: z.enum(["surging", "steady", "slipping"]),
    nationalRank: z.number().int().min(1),
    recruitingStage: z.enum(["unranked", "tracked", "offered", "committed"]),
    committedTeamId: z.string().min(1).optional(),
    eligibilityYears: z.number().int().min(0).max(6),
    seasonsPlayed: z.number().int().nonnegative(),
    transferStatus: z.enum(["none", "portal", "transferred"]),
    previousTeamIds: z.array(z.string().min(1)),
    isHero: z.boolean(),
    eligibility: ecosystemPlayerEligibilitySchema,
    talent: ecosystemTalentProfileSchema,
    usagePlan: z.enum(["starter", "rotation", "special-teams", "developmental", "redshirt"]),
    positionHistory: z.array(z.enum(["QB", "RB", "WR", "LB", "CB"])),
    tactical: ecosystemPlayerTacticalProfileSchema,
  })).min(40),
  coaches: z.array(z.object({
    id: z.string().min(1),
    seed: z.string().min(1),
    name: z.string().min(2),
    teamId: z.string().min(1),
    role: z.enum(["head-coach", "coordinator"]),
    age: z.number().int().min(25).max(80),
    reputation: z.number().min(0).max(100),
    development: z.number().min(0).max(100),
    recruiting: z.number().min(0).max(100),
    pressure: z.number().min(0).max(100),
    jobSecurity: z.number().min(0).max(100),
    status: z.enum(["secure", "watched", "hot-seat"]),
    philosophy: z.string().min(2),
    tenureYears: z.number().int().nonnegative(),
    careerWins: z.number().int().nonnegative(),
    careerLosses: z.number().int().nonnegative(),
    previousTeamIds: z.array(z.string().min(1)),
  })).min(10),
  stories: z.array(z.object({
    id: z.string().min(1),
    kind: z.enum(["breakout", "injury", "depth-change", "commitment", "coach-pressure", "coach-move", "upset", "market-shift", "conference-race", "championship", "transfer", "graduation", "enrollment", "investment", "budget-crunch", "nil-battle", "resource-shift", "talent-class", "camp-breakout", "juco-route", "walk-on-route", "roster-plan", "position-change", "redshirt", "scholarship", "offer", "offer-withdrawn", "market-chain", "coach-vacancy", "tactical-change", "scheme-fit", "ranking", "playoff", "award", "rivalry", "bowl", "mentorship", "locker-room-conflict", "leadership", "reconciliation", "staff-friction", "broken-promise"]),
    createdOn: gameDateSchema,
    week: z.number().int().min(1),
    title: z.string().min(2),
    detail: z.string().min(2),
    importance: z.union([z.literal(1), z.literal(2), z.literal(3), z.literal(4), z.literal(5)]),
    teamIds: z.array(z.string().min(1)),
    playerIds: z.array(z.string().min(1)),
    coachIds: z.array(z.string().min(1)),
    relatedToHero: z.boolean(),
  })),
  digest: z.array(z.string().min(2)).max(6),
  market: z.object({
    openScholarships: z.number().int().nonnegative(),
    activeRecruitments: z.number().int().nonnegative(),
    committedPlayers: z.number().int().nonnegative(),
    coachingHotSeats: z.number().int().nonnegative(),
    portalPlayers: z.number().int().nonnegative(),
    coachOpenings: z.number().int().nonnegative(),
    totalRecruitingBudget: z.number().min(0),
    totalNilCapacity: z.number().min(0),
    programsUnderFinancialPressure: z.number().int().nonnegative(),
    annualProspects: z.number().int().nonnegative(),
    jucoProspects: z.number().int().nonnegative(),
    walkOnProspects: z.number().int().nonnegative(),
    nationallyExposedProspects: z.number().int().nonnegative(),
    plannedClassSpots: z.number().int().nonnegative(),
    developmentalPlayers: z.number().int().nonnegative(),
    plannedPositionChanges: z.number().int().nonnegative(),
    activeNegotiations: z.number().int().nonnegative(),
    withdrawnOffers: z.number().int().nonnegative(),
    transferCandidates: z.number().int().nonnegative(),
    lowSchemeFitPlayers: z.number().int().nonnegative(),
    programsInstallingNewSystems: z.number().int().nonnegative(),
  }),
  teamHistory: z.array(z.object({
    id: z.string().min(1),
    seasonYear: z.number().int(),
    teamId: z.string().min(1),
    conferenceId: z.string().min(1),
    wins: z.number().int().nonnegative(),
    losses: z.number().int().nonnegative(),
    conferenceWins: z.number().int().nonnegative(),
    conferenceLosses: z.number().int().nonnegative(),
    finalRating: z.number().min(0).max(100),
    finish: z.number().int().min(1),
    conferenceChampion: z.boolean(),
    headCoachId: z.string().min(1).optional(),
  })),
  transactions: z.array(z.object({
    id: z.string().min(1),
    kind: z.enum(["portal-entry", "transfer", "coach-fired", "coach-hired", "graduation", "recruit-enrolled", "facility-investment", "budget-cut", "nil-commitment", "juco-entry", "walk-on-entry", "talent-enrolled", "position-change", "scholarship-awarded", "redshirt-assigned", "offer-issued", "offer-withdrawn", "commitment", "coach-vacancy", "tactical-change", "scheme-fit"]),
    seasonYear: z.number().int(),
    week: z.number().int().min(1),
    createdOn: gameDateSchema,
    title: z.string().min(2),
    detail: z.string().min(2),
    playerId: z.string().min(1).optional(),
    coachId: z.string().min(1).optional(),
    fromTeamId: z.string().min(1).optional(),
    toTeamId: z.string().min(1).optional(),
    relatedToHero: z.boolean(),
  })),
  talentPipeline: ecosystemTalentPipelineSchema,
  movementMarket: ecosystemMovementMarketSchema,
  competition: ecosystemCompetitionSchema,
  social: ecosystemSocialSchema,
});

const careerMetaSchema = z.object({
  id: z.string().min(1),
  schemaVersion: z.literal(CURRENT_SCHEMA_VERSION),
  sport: z.literal("american-football"),
  worldSeed: z.string().min(1),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
  currentDate: gameDateSchema,
  phase: z.enum(["high-school-preseason", "college-orientation", "college-season"]),
  revision: z.number().int().nonnegative(),
});

const historyEntrySchema = z.object({
  id: z.string().min(1),
  occurredAt: z.string().datetime(),
  type: z.string().min(1),
  title: z.string().min(1),
  description: z.string().min(1),
});

export const careerSaveSchema = z.object({
  meta: careerMetaSchema,
  character: characterSchema,
  life: lifeSchema,
  football: footballSchema,
  relationships: relationshipsSchema,
  world: footballEcosystemSchema,
  history: z.array(historyEntrySchema),
});

export type CareerSave = z.infer<typeof careerSaveSchema>;

export interface CareerIndexRecord {
  id: string;
  displayName: string;
  sport: "american-football";
  phase: "high-school-preseason" | "college-orientation" | "college-season";
  currentDate: string;
  updatedAt: string;
  revision: number;
  position: "QB" | "RB" | "WR" | "LB" | "CB";
  jerseyNumber: number;
  schoolName: string;
  stateCode: string;
  overall: number;
  potentialBand: "role-player" | "starter" | "high-upside" | "national-ceiling";
}
